import { SongRaw } from 'db/src/actors/Songs/models';
import { createSongRaw } from 'db/src/actors/Songs/raw/creator';

export const FIRST_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: 'ぐるぐるカーテン',
    type: 'title',
    creators: {
      lyrics: ['秋元康'],
      compose: ['黒須克彦'],
      arrange: ['湯浅篤'],
      direct: ['操上和美'],
    },
    center: ['ikomarina'],
    fukujin: 'row-1-2',
    formations: {
      firstRow: ['ikutaerika', 'ikomarina', 'hoshinominami'],
      secondRow: [
        'hashimotonanami',
        'matsumurasayuri',
        'shiraishimai',
        'takayamakazumi',
      ],
      thirdRow: [
        'kawamuramahiro',
        'noujouami',
        'nishinonanase',
        'saitouasuka',
        'saitouyuuri',
        'sakuraireika',
        'inouesayuri',
        'nakadakana',
        'ichikirena',
      ],
    },
  }),
  createSongRaw({
    title: '左胸の勇気',
    type: 'under',
    creators: {
      lyrics: ['秋元康'],
      compose: ['小内喜文'],
      arrange: ['佐々木裕'],
    },
    center: ['hatanakaseira'],
    formations: {
      firstRow: [
        'andoumikumo',
        'iwaseyumiko',
        'itounene',
        'hatanakaseira',
        'itoumarika',
        'wadamaaya',
        'nakamotohimeka',
      ],
      secondRow: [
        'saitouchiharu',
        'yamatorina',
        'nagashimaseira',
        'higuchihina',
        'kawagohina',
        'wakatsukiyumi',
        'kashiwayukina',
        'etoumisa',
        'fukagawamai',
        'miyazawaseira',
      ],
    },
  }),
  createSongRaw({
    title: '乃木坂の詩',
    type: 'coupling',
    creators: {
      lyrics: ['秋元康'],
      compose: ['井手コウジ'],
      arrange: ['井手コウジ'],
      direct: ['南流石'],
    },
    center: ['ikomarina'],
    formations: {
      firstRow: [
        'ikomarina',
        'andoumikumo',
        'ikutaerika',
        'ichikirena',
        'itounene',
        'itoumarika',
        'inouesayuri',
        'iwaseyumiko',
        'etoumisa',
        'kashiwayukina',
        'kawagohina',
        'kawamuramahiro',
        'saitouasuka',
        'saitouchiharu',
        'saitouyuuri',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nagashimaseira',
        'nakadakana',
        'nakamotohimeka',
        'nishinonanase',
        'noujouami',
        'hashimotonanami',
        'hatanakaseira',
        'higuchihina',
        'fukagawamai',
        'hoshinominami',
        'matsumurasayuri',
        'miyazawaseira',
        'yamatorina',
        'wakatsukiyumi',
        'wadamaaya',
      ],
    },
  }),
  createSongRaw({
    title: '会いたかったかもしれない',
    type: 'coupling',
    creators: {
      lyrics: ['秋元康'],
      compose: ['BOUNCEBACK', 'MIKOTO'],
      arrange: ['野中雄一'],
      direct: ['久保茂昭'],
    },
    center: ['ikomarina'],
    formations: {
      firstRow: [
        'ikomarina',
        'ikutaerika',
        'ichikirena',
        'itounene',
        'itoumarika',
        'inouesayuri',
        'etoumisa',
        'kawamuramahiro',
        'saitouasuka',
        'saitouyuuri',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nakadakana',
        'nishinonanase',
        'noujouami',
        'hashimotonanami',
        'hoshinominami',
        'matsumurasayuri',
        'miyazawaseira',
      ],
    },
  }),
  createSongRaw({
    title: '失いたくないから',
    type: 'coupling',
    creators: {
      lyrics: ['秋元康'],
      compose: ['蛯原ランス'],
      arrange: ['塩川満己'],
      direct: ['丸山健志'],
    },
    center: ['ikomarina', 'ikutaerika'],
    formations: {
      firstRow: [
        'ikutaerika',
        'ikomarina',
        'ichikirena',
        'inouesayuri',
        'kawamuramahiro',
        'saitouasuka',
        'saitouyuuri',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nakadakana',
        'nagashimaseira',
        'nakamotohimeka',
        'nishinonanase',
        'noujouami',
        'hashimotonanami',
        'hatanakaseira',
        'fukagawamai',
        'hoshinominami',
        'matsumurasayuri',
      ],
    },
  }),
  createSongRaw({
    title: '白い雲にのって',
    type: 'coupling',
    creators: {
      lyrics: ['秋元康'],
      compose: ['太田美知彦'],
      arrange: ['太田美知彦'],
    },
    center: ['ikomarina'],
    formations: {
      firstRow: [
        'ikomarina',
        'andoumikumo',
        'ikutaerika',
        'ichikirena',
        'inouesayuri',
        'iwaseyumiko',
        'kawagohina',
        'kawamuramahiro',
        'saitouasuka',
        'saitouchiharu',
        'saitouyuuri',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nakadakana',
        'nishinonanase',
        'noujouami',
        'hashimotonanami',
        'hoshinominami',
        'matsumurasayuri',
      ],
    },
  }),
];
