import { SongRaw } from 'db/src/actors/Songs/models';
import { createSongRaw } from 'db/src/actors/Songs/raw/creator';

export const EIGHTEENTH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: '逃げ水',
    type: 'title',
    creators: {
      lyrics: ['秋元康'],
      compose: ['谷村庸平'],
      arrange: ['谷村庸平'],
      direct: ['山岸聖太'],
    },
    center: ['oozonomomoko', 'yodayuuki'],
    fukujin: 'row-1-2',
    formations: {
      firstRow: [
        'saitouasuka',
        'shiraishimai',
        'oozonomomoko',
        'yodayuuki',
        'nishinonanase',
        'horimiona',
      ],
      secondRow: [
        'hoshinominami',
        'matsumurasayuri',
        'ikutaerika',
        'akimotomanatsu',
        'etoumisa',
        'takayamakazumi',
      ],
      thirdRow: [
        'itoumarika',
        'shinuchimai',
        'ikomarina',
        'sakuraireika',
        'wakatsukiyumi',
        'inouesayuri',
      ],
    },
  }),
  createSongRaw({
    title: 'アンダー',
    type: 'under',
    creators: {
      lyrics: ['秋元康'],
      compose: ['白土亨'],
      arrange: ['遠藤ナオキ'],
      direct: ['金森孝宏'],
    },
    center: ['nakamotohimeka', 'kitanohinako'],
    formations: {
      firstRow: [
        'higuchihina',
        'watanabemiria',
        'nakamotohimeka',
        'kitanohinako',
        'teradaranze',
        'saitouyuuri',
      ],
      secondRow: [
        'nakadakana',
        'yamazakirena',
        'suzukiayane',
        'itoukarin',
        'itoujunna',
        'saitouchiharu',
      ],
      thirdRow: [
        'noujouami',
        'sagaraiori',
        'kawagohina',
        'kawamuramahiro',
        'sasakikotoko',
        'wadamaaya',
      ],
    },
  }),
  createSongRaw({
    title: '女は一人じゃ眠れない',
    type: 'selected',
    creators: {
      lyrics: ['秋元康'],
      compose: ['小形誠'],
      arrange: ['高橋浩一郎'],
      direct: ['萩原健太郎'],
    },
    center: ['oozonomomoko', 'yodayuuki'],
    formations: {
      firstRow: [
        'saitouasuka',
        'shiraishimai',
        'oozonomomoko',
        'yodayuuki',
        'nishinonanase',
        'horimiona',
      ],
      secondRow: [
        'hoshinominami',
        'matsumurasayuri',
        'ikutaerika',
        'akimotomanatsu',
        'etoumisa',
        'takayamakazumi',
      ],
      thirdRow: [
        'itoumarika',
        'shinuchimai',
        'ikomarina',
        'sakuraireika',
        'wakatsukiyumi',
        'inouesayuri',
      ],
    },
  }),
  createSongRaw({
    title: 'ひと夏の長さより…',
    type: 'selected',
    creators: {
      lyrics: ['秋元康'],
      compose: ['aokado'],
      arrange: ['aokado'],
    },
    center: ['akimotomanatsu', 'matsumurasayuri'],
    formations: {
      firstRow: [
        'akimotomanatsu',
        'matsumurasayuri',
        'ikutaerika',
        'ikomarina',
        'itoumarika',
        'inouesayuri',
        'etoumisa',
        'oozonomomoko',
        'saitouasuka',
        'sakuraireika',
        'shiraishimai',
        'shinuchimai',
        'takayamakazumi',
        'nishinonanase',
        'hoshinominami',
        'horimiona',
        'yodayuuki',
        'wakatsukiyumi',
      ],
    },
  }),
  createSongRaw({
    title: 'ライブ神',
    type: 'second generation',
    creators: {
      lyrics: ['秋元康'],
      compose: ['SaSA'],
      arrange: ['SaSA'],
      direct: ['伊藤衆人'],
    },
    center: ['horimiona'],
    formations: {
      firstRow: ['teradaranze', 'horimiona', 'kitanohinako'],
      secondRow: [
        'yamazakirena',
        'watanabemiria',
        'suzukiayane',
        'shinuchimai',
      ],
      thirdRow: ['itoujunna', 'itoukarin', 'sagaraiori', 'sasakikotoko'],
    },
  }),

  createSongRaw({
    title: '未来の答え',
    type: 'third generation',
    creators: {
      lyrics: ['秋元康'],
      compose: ['板垣祐介'],
      arrange: ['板垣祐介'],
      direct: ['福島真希'],
    },
    center: ['kuboshiori', 'yamashitamizuki'],
    formations: {
      firstRow: ['umezawaminami', 'yamashitamizuki', 'kuboshiori', 'itouriria'],
      secondRow: [
        'iwamotorenka',
        'oozonomomoko',
        'yodayuuki',
        'sakaguchitamami',
      ],
      thirdRow: [
        'nakamurareno',
        'mukaihazuki',
        'yoshidaayanochristie',
        'satoukaede',
      ],
    },
  }),

  createSongRaw({
    title: '泣いたっていいじゃないか?',
    type: 'selected',
    creators: {
      lyrics: ['秋元康'],
      compose: ['K-WONDER', 'SAS3'],
      arrange: ['遠藤ナオキ'],
    },
    center: ['takayamakazumi'],
    formations: {
      firstRow: [
        'takayamakazumi',
        'akimotomanatsu',
        'ikutaerika',
        'ikomarina',
        'itoumarika',
        'inouesayuri',
        'etoumisa',
        'oozonomomoko',
        'saitouasuka',
        'sakuraireika',
        'shiraishimai',
        'shinuchimai',
        'nishinonanase',
        'hoshinominami',
        'horimiona',
        'matsumurasayuri',
        'yodayuuki',
        'wakatsukiyumi',
      ],
    },
  }),
];
