import { SongRaw } from 'db/src/actors/Songs/models';
import { createSongRaw } from 'db/src/actors/Songs/raw/creator';

export const TWENTIETH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: 'シンクロニシティ',
    type: 'title',
    creators: {
      lyrics: ['秋元康'],
      compose: ['シライシ紗トリ'],
      arrange: ['シライシ紗トリ'],
      direct: ['池田一真'],
    },
    center: ['shiraishimai'],
    fukujin: 'row-1-2',
    formations: {
      firstRow: [
        'yamashitamizuki',
        'horimiona',
        'ikutaerika',
        'shiraishimai',
        'nishinonanase',
        'saitouasuka',
        'yodayuuki',
      ],
      secondRow: [
        'sakuraireika',
        'matsumurasayuri',
        'kuboshiori',
        'ikomarina',
        'oozonomomoko',
        'etoumisa',
        'akimotomanatsu',
      ],
      thirdRow: [
        'inouesayuri',
        'shinuchimai',
        'takayamakazumi',
        'hoshinominami',
        'wakatsukiyumi',
        'higuchihina',
        'teradaranze',
      ],
    },
  }),
  createSongRaw({
    title: '新しい世界',
    type: 'under',
    creators: {
      lyrics: ['秋元康'],
      compose: ['古川貴浩'],
      arrange: ['古川貴浩'],
      direct: ['横堀光範'],
    },
    center: ['suzukiayane'],
    formations: {
      firstRow: [
        'umezawaminami',
        'watanabemiria',
        'nakadakana',
        'suzukiayane',
        'saitouyuuri',
        'yamazakirena',
        'itouriria',
      ],
      secondRow: [
        'mukaihazuki',
        'itoukarin',
        'iwamotorenka',
        'itoujunna',
        'sakaguchitamami',
        'saitouchiharu',
        'satoukaede',
      ],
      thirdRow: [
        'noujouami',
        'kawagohina',
        'yoshidaayanochristie',
        'sasakikotoko',
        'nakamurareno',
        'wadamaaya',
        'sagaraiori',
      ],
    },
  }),
  createSongRaw({
    title: 'Against',
    type: 'first generation',
    creators: {
      lyrics: ['秋元康'],
      compose: ['古川貴浩'],
      arrange: ['古川貴浩'],
      direct: ['丸山健志'],
    },
    center: ['ikomarina'],
    formations: {
      firstRow: [
        'saitouasuka',
        'hoshinominami',
        'ikomarina',
        'ikutaerika',
        'nishinonanase',
      ],
      secondRow: [
        'etoumisa',
        'wakatsukiyumi',
        'takayamakazumi',
        'shiraishimai',
        'matsumurasayuri',
        'akimotomanatsu',
        'sakuraireika',
      ],
      thirdRow: [
        'wadamaaya',
        'inouesayuri',
        'noujouami',
        'saitouchiharu',
        'higuchihina',
        'nakadakana',
        'kawagohina',
        'saitouyuuri',
      ],
    },
  }),
  createSongRaw({
    title: '雲になればいい',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['丸谷マナブ'],
      arrange: ['丸谷マナブ'],
    },
    unit: '藤桜梨',
    formations: {
      firstRow: ['ikutaerika', 'etoumisa', 'sakuraireika'],
    },
  }),
  createSongRaw({
    title: 'スカウトマン',
    type: 'second generation',
    creators: {
      lyrics: ['秋元康'],
      compose: ['SaSA'],
      arrange: ['SaSA'],
      direct: ['中村太洸'],
    },
    center: ['horimiona'],
    formations: {
      firstRow: ['yamazakirena', 'horimiona', 'suzukiayane'],
      secondRow: ['teradaranze', 'shinuchimai'],
      thirdRow: [
        'itoujunna',
        'itoukarin',
        'watanabemiria',
        'suzukiayane',
        'sagaraiori',
      ],
    },
  }),
  createSongRaw({
    title: 'トキトキメキメキ',
    type: 'third generation',
    creators: {
      lyrics: ['秋元康'],
      compose: ['中山聡', '足立優'],
      arrange: ['中山聡', '足立優'],
      direct: ['伊藤衆人'],
    },
    center: ['iwamotorenka'],
    formations: {
      firstRow: ['nakamurareno', 'iwamotorenka', 'sakaguchitamami'],
      secondRow: [
        'umezawaminami',
        'yodayuuki',
        'yamashitamizuki',
        'oozonomomoko',
        'kuboshiori',
      ],
      thirdRow: [
        'yoshidaayanochristie',
        'mukaihazuki',
        'itouriria',
        'satoukaede',
      ],
    },
  }),
  createSongRaw({
    title: '言霊砲',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['Ryota Saito', 'TomoLow'],
      arrange: ['Ryota Saito', 'TomoLow'],
    },
    unit: 'いもうと坂',
    formations: {
      firstRow: ['kuboshiori', 'yodayuuki', 'yamashitamizuki', 'oozonomomoko'],
    },
  }),
];
