import { SongRaw } from 'db/src/actors/Songs/models';
import { createSongRaw } from 'db/src/actors/Songs/raw/creator';

export const THIRD_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: '走れ!Bicycle',
    type: 'title',
    creators: {
      lyrics: ['秋元康'],
      compose: ['Shusui', '伊藤涼', '木村篤史', 'ヒロイズム'],
      arrange: ['湯浅篤'],
      direct: ['中島哲也'],
    },
    center: ['ikomarina'],
    fukujin: [
      'ikutaerika',
      'ikomarina',
      'hoshinominami',
      'hashimotonanami',
      'shiraishimai',
      'matsumurasayuri',
      'nishinonanase',
    ],
    formations: {
      firstRow: ['ikutaerika', 'ikomarina', 'hoshinominami', 'sakuraireika'],
      secondRow: [
        'nakadakana',
        'hashimotonanami',
        'shiraishimai',
        'matsumurasayuri',
        'nishinonanase',
        'takayamakazumi',
      ],
      thirdRow: [
        'saitouyuuri',
        'wakatsukiyumi',
        'inouesayuri',
        'ichikirena',
        'itoumarika',
        'fukagawamai',
      ],
    },
  }),
  createSongRaw({
    title: '涙がまだ悲しみだった頃',
    type: 'under',
    creators: {
      lyrics: ['秋元康'],
      compose: ['内田智之'],
      arrange: ['TATOO'],
      direct: ['関和亮'],
    },
    center: ['itounene'],
    formations: {
      firstRow: ['higuchihina', 'itounene', 'saitouasuka'],
      secondRow: ['etoumisa', 'noujouami', 'kawagohina'],
      thirdRow: [
        'kawamuramahiro',
        'kashiwayukina',
        'yamatorina',
        'nagashimaseira',
      ],
      fourthRow: [
        'miyazawaseira',
        'andoumikumo',
        'hatanakaseira',
        'iwaseyumiko',
        'wadamaaya',
        'nakamotohimeka',
        'saitouchiharu',
      ],
    },
  }),
  createSongRaw({
    title: 'せっかちなかたつむり',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['山本加津彦'],
      arrange: ['湯浅篤'],
      direct: ['中村太洸'],
    },
    center: ['matsumurasayuri'],
    formations: {
      firstRow: [
        'shiraishimai',
        'takayamakazumi',
        'nakadakana',
        'nishinonanase',
        'hashimotonanami',
        'fukagawamai',
        'matsumurasayuri',
      ],
    },
  }),
  createSongRaw({
    title: '人はなぜ走るのか?',
    type: 'selected',
    creators: {
      lyrics: ['秋元康'],
      compose: ['キタムラタケシ', '田上陽一'],
      arrange: ['田上陽一'],
      direct: ['久保茂昭'],
    },
    center: ['ikomarina'],
    formations: {
      firstRow: [
        'ikomarina',
        'ikutaerika',
        'ichikirena',
        'itoumarika',
        'inouesayuri',
        'kashiwayukina',
        'saitouchiharu',
        'saitouyuuri',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nakadakana',
        'nagashimaseira',
        'nishinonanase',
        'hashimotonanami',
        'fukagawamai',
        'hoshinominami',
        'matsumurasayuri',
        'miyazawaseira',
        'yamatorina',
        'wakatsukiyumi',
      ],
    },
  }),
  createSongRaw({
    title: '音が出ないギター',
    type: 'coupling',
    creators: {
      lyrics: ['秋元康'],
      compose: ['Jam9', 'ArmySlick'],
      arrange: ['シライシ紗トリ'],
      direct: ['丸山健志'],
    },
    center: ['ikomarina'],
    formations: {
      firstRow: [
        'ikomarina',
        'ikutaerika',
        'ichikirena',
        'itounene',
        'itoumarika',
        'inouesayuri',
        'iwaseyumiko',
        'etoumisa',
        'kawamuramahiro',
        'saitouyuuri',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nakadakana',
        'nishinonanase',
        'noujouami',
        'hashimotonanami',
        'fukagawamai',
        'hoshinominami',
        'matsumurasayuri',
        'wakatsukiyumi',
      ],
    },
  }),
  createSongRaw({
    title: '海流の島よ',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['Akira Sunset'],
      arrange: ['京田誠一'],
    },
    center: ['saitouasuka'],
    formations: {
      firstRow: [
        'andoumikumo',
        'kawagohina',
        'saitouasuka',
        'nakamotohimeka',
        'hatanakaseira',
        'higuchihina',
        'wadamaaya',
      ],
    },
  }),
];
