import { SongRaw } from 'db/src/actors/Songs/models';
import { createSongRaw } from 'db/src/actors/Songs/raw/creator';

export const EIGHTH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: '気づいたら片想い',
    type: 'title',
    creators: {
      lyrics: ['秋元康'],
      compose: ['Akira Sunset'],
      arrange: ['湯浅篤'],
      direct: ['柳沢翔'],
    },
    center: ['nishinonanase'],
    fukujin: 'row-1',
    formations: {
      firstRow: [
        'horimiona',
        'shiraishimai',
        'nishinonanase',
        'hashimotonanami',
        'ikomarina',
      ],
      secondRow: [
        'sakuraireika',
        'wakatsukiyumi',
        'ikutaerika',
        'matsumurasayuri',
        'fukagawamai',
      ],
      thirdRow: [
        'kawamuramahiro',
        'kitanohinako',
        'higuchihina',
        'akimotomanatsu',
        'wadamaaya',
        'takayamakazumi',
      ],
    },
  }),
  createSongRaw({
    title: '生まれたままで',
    type: 'under',
    creators: {
      lyrics: ['秋元康'],
      compose: ['田中俊亮'],
      arrange: ['鈴木裕明'],
      direct: ['久保茂昭'],
    },
    center: ['itoumarika'],
    formations: {
      firstRow: [
        'inouesayuri',
        'saitouasuka',
        'itoumarika',
        'hoshinominami',
        'saitouyuuri',
      ],
      secondRow: [
        'nagashimaseira',
        'nakadakana',
        'etoumisa',
        'kawagohina',
        'nakamotohimeka',
      ],
      thirdRow: [
        'saitouchiharu',
        'itounene',
        'ichikirena',
        'shinuchimai',
        'hatanakaseira',
        'yamatorina',
        'noujouami',
      ],
    },
  }),
  createSongRaw({
    title: 'ロマンスのスタート',
    type: 'selected',
    creators: {
      lyrics: ['秋元康'],
      compose: ['押田誠'],
      arrange: ['佐々木聡作', '押田誠'],
      direct: ['丸山健志'],
    },
    center: ['nishinonanase'],
    formations: {
      firstRow: [
        'horimiona',
        'shiraishimai',
        'nishinonanase',
        'hashimotonanami',
        'ikomarina',
      ],
      secondRow: [
        'sakuraireika',
        'wakatsukiyumi',
        'ikomarina',
        'matsumurasayuri',
        'fukagawamai',
      ],
      thirdRow: [
        'kawamuramahiro',
        'kitanohinako',
        'higuchihina',
        'akimotomanatsu',
        'wadamaaya',
        'takayamakazumi',
      ],
    },
  }),
  createSongRaw({
    title: '吐息のメソッド',
    type: 'selected',
    creators: {
      lyrics: ['秋元康'],
      compose: ['田中明仁'],
      arrange: ['TATOO'],
    },
    formations: {
      firstRow: [
        'akimotomanatsu',
        'ikutaerika',
        'ikomarina',
        'itoumarika',
        'inouesayuri',
        'kawamuramahiro',
        'kitanohinako',
        'saitouasuka',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nishinonanase',
        'hashimotonanami',
        'higuchihina',
        'fukagawamai',
        'hoshinominami',
        'horimiona',
        'matsumurasayuri',
        'wakatsukiyumi',
        'wadamaaya',
      ],
    },
  }),
  createSongRaw({
    title: '孤独兄弟',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['Soulife'],
      arrange: ['Soulife'],
      direct: ['池田一真'],
    },
    unit: '孤独兄弟',
    formations: {
      firstRow: ['shiraishimai', 'hashimotonanami'],
    },
  }),
  createSongRaw({
    title: 'ダンケシェーン',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['Akira Sunset', 'C#'],
      arrange: ['Akira Sunset', 'C#'],
    },
    center: ['ikutaerika'],
    formations: {
      firstRow: [
        'ikutaerika',
        'ikomarina',
        'sakuraireika',
        'nishinonanase',
        'fukagawamai',
        'horimiona',
        'matsumurasayuri',
        'wakatsukiyumi',
      ],
    },
  }),
];
