import { FIRST_SINGLE_SONGS } from './1';
import { TENTH_SINGLE_SONGS } from './10';
import { ELEVENTH_SINGLE_SONGS } from './11';
import { TWELFTH_SINGLE_SONGS } from './12';
import { THIRTEENTH_SINGLE_SONGS } from './13';
import { FOURTEENTH_SINGLE_SONGS } from './14';
import { FIFTEENTH_SINGLE_SONGS } from './15';
import { SIXTEENTH_SINGLE_SONGS } from './16';
import { SEVENTEENTH_SINGLE_SONGS } from './17';
import { EIGHTEENTH_SINGLE_SONGS } from './18';
import { NINETEENTH_SINGLE_SONGS } from './19';
import { SECOND_SINGLE_SONGS } from './2';
import { TWENTIETH_SINGLE_SONGS } from './20';
import { TWENTY_FIRST_SINGLE_SONGS } from './21';
import { TWENTY_SECOND_SINGLE_SONGS } from './22';
import { TWENTY_THIRD_SINGLE_SONGS } from './23';
import { TWENTY_FOURTH_SINGLE_SONGS } from './24';
import { TWENTY_FIFTH_SINGLE_SONGS } from './25';
import { THIRD_SINGLE_SONGS } from './3';
import { FOURTH_SINGLE_SONGS } from './4';
import { FIFTH_SINGLE_SONGS } from './5';
import { SIXTH_SINGLE_SONGS } from './6';
import { SEVENTH_SINGLE_SONGS } from './7';
import { EIGHTH_SINGLE_SONGS } from './8';
import { NINTH_SINGLE_SONGS } from './9';
import { TWENTY_SIXTH_SINGLE_SONGS } from './26';
import { TWENTY_SEVENTH_SINGLE_SONGS } from './27';
import { TWENTY_EIGHTH_SINGLE_SONGS } from './28';
import { TWENTY_NINTH_SINGLE_SONGS } from './29';
import { THIRTIETH_SINGLE_SONGS } from './30';
import { THIRTY_FIRST_SINGLE_SONGS } from './31';
import { SongRaw } from 'db/src/actors/Songs/models';

export const SINGLE_SONGS: SongRaw[] = [
  ...FIRST_SINGLE_SONGS,
  ...SECOND_SINGLE_SONGS,
  ...THIRD_SINGLE_SONGS,
  ...FOURTH_SINGLE_SONGS,
  ...FIFTH_SINGLE_SONGS,
  ...SIXTH_SINGLE_SONGS,
  ...SEVENTH_SINGLE_SONGS,
  ...EIGHTH_SINGLE_SONGS,
  ...NINTH_SINGLE_SONGS,
  ...TENTH_SINGLE_SONGS,
  ...ELEVENTH_SINGLE_SONGS,
  ...TWELFTH_SINGLE_SONGS,
  ...THIRTEENTH_SINGLE_SONGS,
  ...FOURTEENTH_SINGLE_SONGS,
  ...FIFTEENTH_SINGLE_SONGS,
  ...SIXTEENTH_SINGLE_SONGS,
  ...SEVENTEENTH_SINGLE_SONGS,
  ...EIGHTEENTH_SINGLE_SONGS,
  ...NINETEENTH_SINGLE_SONGS,
  ...TWENTIETH_SINGLE_SONGS,
  ...TWENTY_FIRST_SINGLE_SONGS,
  ...TWENTY_SECOND_SINGLE_SONGS,
  ...TWENTY_THIRD_SINGLE_SONGS,
  ...TWENTY_FOURTH_SINGLE_SONGS,
  ...TWENTY_FIFTH_SINGLE_SONGS,
  ...TWENTY_SIXTH_SINGLE_SONGS,
  ...TWENTY_SEVENTH_SINGLE_SONGS,
  ...TWENTY_EIGHTH_SINGLE_SONGS,
  ...TWENTY_NINTH_SINGLE_SONGS,
  ...THIRTIETH_SINGLE_SONGS,
  ...THIRTY_FIRST_SINGLE_SONGS,
];
