import { SongRaw } from 'db/src/actors/Songs/models';
import { createSongRaw } from 'db/src/actors/Songs/raw/creator';

export const FIRST_ALBUM_SONGS: SongRaw[] = [
  createSongRaw({
    title: '誰かは味方',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['宮坂聡彦'],
      arrange: ['佐々木裕'],
    },
    formations: {
      firstRow: ['etoumisa', 'sakuraireika', 'wakatsukiyumi'],
    },
  }),
  createSongRaw({
    title: '革命の馬',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['伊勢佳史'],
      arrange: ['伊勢佳史'],
    },
    formations: {
      firstRow: [
        'akimotomanatsu',
        'shiraishimai',
        'takayamakazumi',
        'hashimotonanami',
        'fukagawamai',
        'matsumurasayuri',
      ],
    },
  }),
  createSongRaw({
    title: '僕がいる場所',
    type: 'selected',
    creators: {
      lyrics: ['秋元康'],
      compose: ['杉山勝彦'],
      arrange: ['杉山勝彦', '有木竜郎'],
    },
    center: ['ikutaerika'],
    formations: {
      firstRow: [
        'ikutaerika',
        'akimotomanatsu',
        'ikomarina',
        'etoumisa',
        'saitouchiharu',
        'sakuraireika',
        'shiraishimai',
        'takayamakazumi',
        'nishinonanase',
        'hashimotonanami',
        'fukagawamai',
        'horimiona',
        'hoshinominami',
        'matsuirena',
        'matsumurasayuri',
        'wakatsukiyumi',
      ],
    },
  }),
  createSongRaw({
    title: 'あなたのために弾きたい',
    type: 'solo',
    creators: {
      lyrics: ['秋元康'],
      compose: ['近藤圭一'],
      arrange: ['樫原伸彦'],
    },
    solo: 'ikutaerika',
  }),
  createSongRaw({
    title: '傾斜する',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['須藤哲平', '長谷川湊'],
      arrange: ['佐々木裕'],
    },
    center: ['kojimaharuna'],
    unit: 'こじ坂46',
    formations: {
      firstRow: [
        'kojimaharuna',
        'ikomarina',
        'itoujunna',
        'kawagohina',
        'kawamuramahiro',
        'saitouyuuri',
        'sagaraiori',
        'sasakikotoko',
        'suzukiayane',
        'teradaranze',
        'nakadakana',
        'nagashimaseira',
        'noujouami',
        'yamazakirena',
        'watanabemiria',
        'wadamaaya',
      ],
    },
  }),
  createSongRaw({
    title: 'なぞの落書き',
    type: 'unit',
    creators: {
      lyrics: ['秋元康'],
      compose: ['片桐周太郎'],
      arrange: ['野中"まさ"雄一'],
    },
    formations: {
      firstRow: ['saitouasuka', 'hoshinominami', 'horimiona'],
    },
  }),
  createSongRaw({
    title: '自由の彼方',
    type: 'under',
    creators: {
      lyrics: ['秋元康'],
      compose: ['山田智和'],
      arrange: ['住谷翔平'],
    },
    center: ['inouesayuri'],
    formations: {
      firstRow: [
        'inouesayuri',
        'itoukarin',
        'itoujunna',
        'itoumarika',
        'kawamuramahiro',
        'kawagohina',
        'kitanohinako',
        'saitouasuka',
        'saitouyuuri',
        'sagaraiori',
        'sasakikotoko',
        'shinuchimai',
        'suzukiayane',
        'teradaranze',
        'nakadakana',
        'nagashimaseira',
        'nakamotohimeka',
        'noujouami',
        'hatanakaseira',
        'higuchihina',
        'yamazakirena',
        'yamatorina',
        'watanabemiria',
        'wadamaaya',
      ],
    },
  }),
  createSongRaw({
    title: 'ひとりよがり',
    type: 'solo',
    creators: {
      lyrics: ['秋元康'],
      compose: ['杉山勝彦'],
      arrange: ['杉山勝彦', '有木竜郎'],
    },
    solo: 'nishinonanase',
  }),
];
