import { SongRaw } from "server/actors/Songs/models";
import { createSongRaw } from "server/actors/Songs/raw/creator";
import { SongType } from "server/constants/commons";
import { MemberName } from "server/constants/names";
import { SongTitle } from "server/constants/songs";

export const THIRD_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: SongTitle.HashireBicycle,
    type: SongType.Title,
    creators: {
      lyrics: ["秋元康"],
      compose: ["Shusui", "伊藤涼", "木村篤史", "ヒロイズム"],
      arrange: ["湯浅篤"],
      direct: ["中島哲也"],
    },
    center: [MemberName.IkomaRina],
    fukujin: [
      MemberName.IkutaErika,
      MemberName.IkomaRina,
      MemberName.HoshinoMinami,
      MemberName.HashimotoNanami,
      MemberName.ShiraishiMai,
      MemberName.MatsumuraSayuri,
      MemberName.NishinoNanase,
    ],
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.HoshinoMinami,
        MemberName.SakuraiReika,
      ],
      secondRow: [
        MemberName.NakadaKana,
        MemberName.HashimotoNanami,
        MemberName.ShiraishiMai,
        MemberName.MatsumuraSayuri,
        MemberName.NishinoNanase,
        MemberName.TakayamaKazumi,
      ],
      thirdRow: [
        MemberName.SaitouYuuri,
        MemberName.WakatsukiYumi,
        MemberName.InoueSayuri,
        MemberName.IchikiRena,
        MemberName.ItouMarika,
        MemberName.FukagawaMai,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Namidagamadakanashimidattakoro,
    type: SongType.Under,
    creators: {
      lyrics: ["秋元康"],
      compose: ["内田智之"],
      arrange: ["TATOO"],
      direct: ["関和亮"],
    },
    center: [MemberName.ItouNene],
    formations: {
      firstRow: [
        MemberName.HiguchiHina,
        MemberName.ItouNene,
        MemberName.SaitouAsuka,
      ],
      secondRow: [
        MemberName.EtouMisa,
        MemberName.NoujouAmi,
        MemberName.KawagoHina,
      ],
      thirdRow: [
        MemberName.KawamuraMahiro,
        MemberName.KashiwaYukina,
        MemberName.YamatoRina,
        MemberName.NagashimaSeira,
      ],
      fourthRow: [
        MemberName.MiyazawaSeira,
        MemberName.AndouMikumo,
        MemberName.HatanakaSeira,
        MemberName.IwaseYumiko,
        MemberName.WadaMaaya,
        MemberName.NakamotoHimeka,
        MemberName.SaitouChiharu,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Sekkachinakatatsumuri,
    type: SongType.Unit,
    creators: {
      lyrics: ["秋元康"],
      compose: ["山本加津彦"],
      arrange: ["湯浅篤"],
      direct: ["中村太洸"],
    },
    center: [MemberName.MatsumuraSayuri],
    formations: {
      firstRow: [
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.NishinoNanase,
        MemberName.HashimotoNanami,
        MemberName.FukagawaMai,
        MemberName.MatsumuraSayuri,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Hitohanazehashirunoka,
    type: SongType.Selected,
    creators: {
      lyrics: ["秋元康"],
      compose: ["キタムラタケシ", "田上陽一"],
      arrange: ["田上陽一"],
      direct: ["久保茂昭"],
    },
    center: [MemberName.IkomaRina],
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.IchikiRena,
        MemberName.ItouMarika,
        MemberName.InoueSayuri,
        MemberName.KashiwaYukina,
        MemberName.SaitouChiharu,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.NagashimaSeira,
        MemberName.NishinoNanase,
        MemberName.HashimotoNanami,
        MemberName.FukagawaMai,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.MiyazawaSeira,
        MemberName.YamatoRina,
        MemberName.WakatsukiYumi,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.OtogadenaiGuitar,
    type: SongType.Coupling,
    creators: {
      lyrics: ["秋元康"],
      compose: ["Jam9", "ArmySlick"],
      arrange: ["シライシ紗トリ"],
      direct: ["丸山健志"],
    },
    center: [MemberName.IkomaRina],
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.IchikiRena,
        MemberName.ItouNene,
        MemberName.ItouMarika,
        MemberName.InoueSayuri,
        MemberName.IwaseYumiko,
        MemberName.EtouMisa,
        MemberName.KawamuraMahiro,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.NishinoNanase,
        MemberName.NoujouAmi,
        MemberName.HashimotoNanami,
        MemberName.FukagawaMai,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.WakatsukiYumi,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Kairyuunoshimayo,
    type: SongType.Unit,
    creators: {
      lyrics: ["秋元康"],
      compose: ["Akira Sunset"],
      arrange: ["京田誠一"],
    },
    center: [MemberName.SaitouAsuka],
    formations: {
      firstRow: [
        MemberName.AndouMikumo,
        MemberName.KawagoHina,
        MemberName.SaitouAsuka,
        MemberName.NakamotoHimeka,
        MemberName.HatanakaSeira,
        MemberName.HiguchiHina,
        MemberName.WadaMaaya,
      ],
    },
  }),
];
