import { MemberRaw } from 'db/src/actors/Members/models';
import { createMemberRaw } from 'db/src/actors/Members/raw/creator';

export const FIFTH_GEN_MEMBERS: MemberRaw[] = [
  createMemberRaw({
    name: 'inouenagi',
    nameNotations: ['井上', '和', 'いのうえ', 'なぎ', 'inoue', 'nagi'],
    join: 'fifth',
    birthday: '2005-02-17',
    height: 156,
    bloodType: 'b',
    origin: '神奈川県',
  }),
  createMemberRaw({
    name: 'ichinosemiku',
    nameNotations: ['一ノ瀬', '美空', 'いちのせ', 'みく', 'ichinose', 'miku'],
    join: 'fifth',
    birthday: '2003-05-24',
    height: 156,
    bloodType: 'b',
    origin: '福岡県',
  }),
  createMemberRaw({
    name: 'sugawarasatsuki',
    nameNotations: [
      '菅原',
      '咲月',
      'すがわら',
      'さつき',
      'sugawara',
      'satsuki',
    ],
    join: 'fifth',
    birthday: '2005-10-31',
    height: 157,
    bloodType: 'a',
    origin: '千葉県',
  }),
  createMemberRaw({
    name: 'ogawaaya',
    nameNotations: ['小川', '彩', 'おがわ', 'あや', 'ogawa', 'aya'],
    join: 'fifth',
    birthday: '2007-06-27',
    height: 154,
    bloodType: 'b',
    origin: '千葉県',
  }),
  createMemberRaw({
    name: 'tomisatonao',
    nameNotations: ['冨里', '奈央', 'とみさと', 'なお', 'tomisato', 'nao'],
    join: 'fifth',
    birthday: '2006-09-18',
    height: 164,
    bloodType: 'o',
    origin: '千葉県',
  }),
  createMemberRaw({
    name: 'okudairoha',
    nameNotations: ['奥田', 'いろは', 'おくだ', 'いろは', 'okuta', 'iroha'],
    join: 'fifth',
    birthday: '2005-08-20',
    height: 157,
    bloodType: 'a',
    origin: '千葉県',
  }),
  createMemberRaw({
    name: 'nakanishiaruno',
    nameNotations: [
      '中西',
      'アルノ',
      'なかにし',
      'あるの',
      'nakanishi',
      'aruno',
    ],
    join: 'fifth',
    birthday: '2003-03-17',
    height: 157,
    bloodType: 'a',
    origin: '千葉県',
  }),
  createMemberRaw({
    name: 'iokimao',
    nameNotations: ['五百城', '茉央', 'いおき', 'まお', 'ioki', 'mao'],
    join: 'fifth',
    birthday: '2005-07-29',
    height: 166,
    bloodType: 'o',
    origin: '兵庫県',
  }),
  createMemberRaw({
    name: 'ikedateresa',
    nameNotations: ['池田', '瑛紗', 'いけだ', 'てれさ', 'ikeda', 'teresa'],
    join: 'fifth',
    birthday: '2002-05-12',
    height: 159,
    bloodType: 'unknown',
    origin: '東京都',
  }),
];
