export enum Birthplace {
  Tokyo = '東京都',
  Saitama = '埼玉県',
  Kanagawa = '神奈川県',
  Oita = '大分県',
  Okinawa = '沖縄県',
  Kagoshima = '鹿児島県',
  Hokkaido = '北海道',
  Miyagi = '宮城県',
  Aichi = '愛知県',
  Gunma = '群馬県',
  Akita = '秋田県',
  Chiba = '千葉県',
  Osaka = '大阪府',
  Gifu = '岐阜県',
  Fukuoka = '福岡県',
  Hiroshima = '広島県',
  Tochigi = '栃木県',
  Okayama = '岡山県',
  Nagasaki = '長崎県',
  Shizuoka = '静岡県',
  Iwate = '岩手県',
  Kyoto = '京都府',
  California = 'California, US',
  Düsseldorf = 'Düsseldorf, Germany',
}
