export type SongType =
  | 'none'
  | 'title'
  | 'coupling'
  | 'selected'
  | 'lead'
  | 'under'
  | 'unit'
  | 'solo'
  | 'first generation'
  | 'second generation'
  | 'third generation'
  | 'fourth generation'
  | 'fifth generation'
  | 'special';
