import { SongRaw } from "server/actors/Songs/models";
import { createSongRaw } from "server/actors/Songs/raw/creator";
import { FukujinType, SongType } from "server/constants/commons";
import { MemberName } from "server/constants/names";
import { SongTitle } from "server/constants/songs";

export const EIGHTEENTH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: SongTitle.Nigemizu,
    type: SongType.Title,
    creators: {
      lyrics: ["秋元康"],
      compose: ["谷村庸平"],
      arrange: ["谷村庸平"],
      direct: ["山岸聖太"],
    },
    center: [MemberName.OozonoMomoko, MemberName.YodaYuuki],
    fukujin: FukujinType.RowOneTwo,
    formations: {
      firstRow: [
        MemberName.SaitouAsuka,
        MemberName.ShiraishiMai,
        MemberName.OozonoMomoko,
        MemberName.YodaYuuki,
        MemberName.NishinoNanase,
        MemberName.HoriMiona,
      ],
      secondRow: [
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.IkutaErika,
        MemberName.AkimotoManatsu,
        MemberName.EtouMisa,
        MemberName.TakayamaKazumi,
      ],
      thirdRow: [
        MemberName.ItouMarika,
        MemberName.ShinuchiMai,
        MemberName.IkomaRina,
        MemberName.SakuraiReika,
        MemberName.WakatsukiYumi,
        MemberName.InoueSayuri,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Under,
    type: SongType.Under,
    creators: {
      lyrics: ["秋元康"],
      compose: ["白土亨"],
      arrange: ["遠藤ナオキ"],
      direct: ["金森孝宏"],
    },
    center: [MemberName.NakamotoHimeka, MemberName.KitanoHinako],
    formations: {
      firstRow: [
        MemberName.HiguchiHina,
        MemberName.WatanabeMiria,
        MemberName.NakamotoHimeka,
        MemberName.KitanoHinako,
        MemberName.TeradaRanze,
        MemberName.SaitouYuuri,
      ],
      secondRow: [
        MemberName.NakadaKana,
        MemberName.YamazakiRena,
        MemberName.SuzukiAyane,
        MemberName.ItouKarin,
        MemberName.ItouJunna,
        MemberName.SaitouChiharu,
      ],
      thirdRow: [
        MemberName.NoujouAmi,
        MemberName.SagaraIori,
        MemberName.KawagoHina,
        MemberName.KawamuraMahiro,
        MemberName.SasakiKotoko,
        MemberName.WadaMaaya,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Onnahahitorijanemurenai,
    type: SongType.Selected,
    creators: {
      lyrics: ["秋元康"],
      compose: ["小形誠"],
      arrange: ["高橋浩一郎"],
      direct: ["萩原健太郎"],
    },
    center: [MemberName.OozonoMomoko, MemberName.YodaYuuki],
    formations: {
      firstRow: [
        MemberName.AkimotoManatsu,
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.ItouMarika,
        MemberName.InoueSayuri,
        MemberName.EtouMisa,
        MemberName.OozonoMomoko,
        MemberName.SaitouAsuka,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.ShinuchiMai,
        MemberName.TakayamaKazumi,
        MemberName.NishinoNanase,
        MemberName.HoshinoMinami,
        MemberName.HoriMiona,
        MemberName.MatsumuraSayuri,
        MemberName.YodaYuuki,
        MemberName.WakatsukiYumi,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Hitonatsunonagasayori,
    type: SongType.Selected,
    creators: {
      lyrics: ["秋元康"],
      compose: ["aokado"],
      arrange: ["aokado"],
    },
    center: [MemberName.AkimotoManatsu, MemberName.MatsumuraSayuri],
    formations: {
      firstRow: [
        MemberName.AkimotoManatsu,
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.ItouMarika,
        MemberName.InoueSayuri,
        MemberName.EtouMisa,
        MemberName.OozonoMomoko,
        MemberName.SaitouAsuka,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.ShinuchiMai,
        MemberName.TakayamaKazumi,
        MemberName.NishinoNanase,
        MemberName.HoshinoMinami,
        MemberName.HoriMiona,
        MemberName.MatsumuraSayuri,
        MemberName.YodaYuuki,
        MemberName.WakatsukiYumi,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.LiveShin,
    type: SongType.SecondGeneration,
    creators: {
      lyrics: ["秋元康"],
      compose: ["SaSA"],
      arrange: ["SaSA"],
      direct: ["伊藤衆人"],
    },
    center: [MemberName.HoriMiona],
    formations: {
      firstRow: [
        MemberName.TeradaRanze,
        MemberName.HoriMiona,
        MemberName.KitanoHinako,
      ],
      secondRow: [
        MemberName.YamazakiRena,
        MemberName.WatanabeMiria,
        MemberName.SuzukiAyane,
        MemberName.ShinuchiMai,
      ],
      thirdRow: [
        MemberName.ItouJunna,
        MemberName.ItouKarin,
        MemberName.SagaraIori,
        MemberName.SasakiKotoko,
      ],
    },
  }),

  createSongRaw({
    title: SongTitle.Mirainokotae,
    type: SongType.ThirdGeneration,
    creators: {
      lyrics: ["秋元康"],
      compose: ["板垣祐介"],
      arrange: ["板垣祐介"],
      direct: ["福島真希"],
    },
    center: [MemberName.KuboShiori, MemberName.YamashitaMizuki],
    formations: {
      firstRow: [
        MemberName.UmezawaMinami,
        MemberName.YamashitaMizuki,
        MemberName.KuboShiori,
        MemberName.ItouRiria,
      ],
      secondRow: [
        MemberName.IwamotoRenka,
        MemberName.OozonoMomoko,
        MemberName.YodaYuuki,
        MemberName.SakaguchiTamami,
      ],
      thirdRow: [
        MemberName.NakamuraReno,
        MemberName.MukaiHazuki,
        MemberName.YoshidaAyanoChristie,
        MemberName.SatouKaede,
      ],
    },
  }),

  createSongRaw({
    title: SongTitle.Naitatteiijanaika,
    type: SongType.Selected,
    creators: {
      lyrics: ["秋元康"],
      compose: ["K-WONDER", "SAS3"],
      arrange: ["遠藤ナオキ"],
    },
    center: [MemberName.TakayamaKazumi],
    formations: {
      firstRow: [
        MemberName.AkimotoManatsu,
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.ItouMarika,
        MemberName.InoueSayuri,
        MemberName.EtouMisa,
        MemberName.OozonoMomoko,
        MemberName.SaitouAsuka,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.ShinuchiMai,
        MemberName.TakayamaKazumi,
        MemberName.NishinoNanase,
        MemberName.HoshinoMinami,
        MemberName.HoriMiona,
        MemberName.MatsumuraSayuri,
        MemberName.YodaYuuki,
        MemberName.WakatsukiYumi,
      ],
    },
  }),
];
