import { SongRaw } from "server/actors/Songs/models";
import { createSongRaw } from "server/actors/Songs/raw/creator";
import { FukujinType, SongType } from "server/constants/commons";
import { MemberName } from "server/constants/names";
import { SongTitle } from "server/constants/songs";

export const TWENTY_FIRST_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: SongTitle.Jikochudeikou,
    type: SongType.Title,
    creators: {
      lyrics: ["秋元康"],
      compose: ["ナスカ"],
      arrange: ['野中"まさ"雄一'],
      direct: ["中村太洸"],
    },
    center: [MemberName.SaitouAsuka],
    fukujin: FukujinType.RowOneTwo,
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.YodaYuuki,
        MemberName.NishinoNanase,
        MemberName.SaitouAsuka,
        MemberName.ShiraishiMai,
        MemberName.HoriMiona,
        MemberName.YamashitaMizuki,
      ],
      secondRow: [
        MemberName.AkimotoManatsu,
        MemberName.EtouMisa,
        MemberName.OozonoMomoko,
        MemberName.UmezawaMinami,
        MemberName.IwamotoRenka,
        MemberName.MatsumuraSayuri,
        MemberName.SakuraiReika,
      ],
      thirdRow: [
        MemberName.TakayamaKazumi,
        MemberName.SaitouYuuri,
        MemberName.WakatsukiYumi,
        MemberName.SuzukiAyane,
        MemberName.HoshinoMinami,
        MemberName.ShinuchiMai,
        MemberName.InoueSayuri,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Sankakunoakichi,
    type: SongType.Under,
    creators: {
      lyrics: ["秋元康"],
      compose: ["Hiroki"],
      arrange: ["Yasutaka.Ishio"],
      direct: ["月田茂"],
    },
    center: [MemberName.NakadaKana],
    formations: {
      firstRow: [
        MemberName.HiguchiHina,
        MemberName.NakadaKana,
        MemberName.ItouRiria,
      ],
      secondRow: [
        MemberName.YamazakiRena,
        MemberName.SakaguchiTamami,
        MemberName.KitanoHinako,
        MemberName.TeradaRanze,
        MemberName.WatanabeMiria,
        MemberName.SatouKaede,
      ],
      thirdRow: [
        MemberName.YoshidaAyanoChristie,
        MemberName.WadaMaaya,
        MemberName.KawagoHina,
        MemberName.NoujouAmi,
        MemberName.NakamuraReno,
        MemberName.ItouKarin,
        MemberName.SasakiKotoko,
        MemberName.MukaiHazuki,
        MemberName.ItouJunna,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Soratobira,
    type: SongType.Selected,
    creators: {
      lyrics: ["秋元康"],
      compose: ["FURUTA", "Dr.Lilcom"],
      arrange: ["Dr.Lilcom"],
      direct: ["伊藤衆人"],
    },
    center: [MemberName.UmezawaMinami],
    formations: {
      firstRow: [
        MemberName.AkimotoManatsu,
        MemberName.IkutaErika,
        MemberName.InoueSayuri,
        MemberName.IwamotoRenka,
        MemberName.UmezawaMinami,
        MemberName.EtouMisa,
        MemberName.OozonoMomoko,
        MemberName.SaitouYuuri,
        MemberName.ShiraishiMai,
        MemberName.ShinuchiMai,
        MemberName.SuzukiAyane,
        MemberName.TakayamaKazumi,
        MemberName.NishinoNanase,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.YamashitaMizuki,
        MemberName.YodaYuuki,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Jibunjanaikanji,
    type: SongType.ThirdGeneration,
    creators: {
      lyrics: ["秋元康"],
      compose: ["ツキダタダシ"],
      arrange: ["ツキダタダシ"],
    },
    center: [MemberName.YamashitaMizuki],
    formations: {
      firstRow: [
        MemberName.ItouRiria,
        MemberName.IwamotoRenka,
        MemberName.UmezawaMinami,
        MemberName.OozonoMomoko,
        MemberName.SakaguchiTamami,
        MemberName.SatouKaede,
        MemberName.NakamuraReno,
        MemberName.MukaiHazuki,
        MemberName.YamashitaMizuki,
        MemberName.YoshidaAyanoChristie,
        MemberName.YodaYuuki,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.KokoronoMonolog,
    type: SongType.Unit,
    creators: {
      lyrics: ["秋元康"],
      compose: ["シライシ紗トリ"],
      arrange: ["シライシ紗トリ"],
      direct: ["英勉"],
    },
    formations: {
      firstRow: [MemberName.ShiraishiMai, MemberName.NishinoNanase],
    },
  }),
  createSongRaw({
    title: SongTitle.Chikyuugamaruinara,
    type: SongType.Unit,
    creators: {
      lyrics: ["秋元康"],
      compose: ["山下孝之"],
      arrange: ["山下孝之"],
      direct: ["沖田修一"],
    },
    formations: {
      firstRow: [
        MemberName.OozonoMomoko,
        MemberName.SaitouAsuka,
        MemberName.YodaYuuki,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Annanisukidattanoni,
    type: SongType.Selected,
    creators: {
      lyrics: ["秋元康"],
      compose: ["木下めろん"],
      arrange: ["木下めろん"],
      direct: [],
    },
    center: [MemberName.SaitouAsuka],
    formations: {
      firstRow: [
        MemberName.AkimotoManatsu,
        MemberName.IkutaErika,
        MemberName.InoueSayuri,
        MemberName.IwamotoRenka,
        MemberName.UmezawaMinami,
        MemberName.EtouMisa,
        MemberName.OozonoMomoko,
        MemberName.SaitouAsuka,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.ShinuchiMai,
        MemberName.SuzukiAyane,
        MemberName.TakayamaKazumi,
        MemberName.NishinoNanase,
        MemberName.HoshinoMinami,
        MemberName.HoriMiona,
        MemberName.MatsumuraSayuri,
        MemberName.YamashitaMizuki,
        MemberName.YodaYuuki,
        MemberName.WakatsukiYumi,
      ],
    },
  }),
];
