import { SongRaw } from 'server/actors/Songs/models';
import { SongType } from 'server/actors/Songs/constants/songType';
import { SONGS } from 'server/actors/Songs/constants/songTitle';
import { createSongRaw } from 'server/actors/Songs/raw/creator';
import { MemberNameKey } from 'server/actors/Members/constants/memberName';

export const DIGITAL_SONGS: SongRaw[] = [
  createSongRaw({
    title: SONGS['世界中の隣人よ'].title,
    type: SongType.Special,
    creators: {
      lyrics: ['秋元康'],
      compose: ['taka'],
      arrange: ['taka'],
      direct: ['横堀光範'],
    },
    formations: {
      firstRow: [
        MemberNameKey.AkimotoManatsu,
        MemberNameKey.IkutaErika,
        MemberNameKey.SaitouAsuka,
        MemberNameKey.ShiraishiMai,
        MemberNameKey.TakayamaKazumi,
        MemberNameKey.NakadaKana,
        MemberNameKey.HiguchiHina,
        MemberNameKey.HoshinoMinami,
        MemberNameKey.MatsumuraSayuri,
        MemberNameKey.WadaMaaya,
        MemberNameKey.ItouJunna,
        MemberNameKey.KitanoHinako,
        MemberNameKey.ShinuchiMai,
        MemberNameKey.SuzukiAyane,
        MemberNameKey.TeradaRanze,
        MemberNameKey.HoriMiona,
        MemberNameKey.YamazakiRena,
        MemberNameKey.WatanabeMiria,
        MemberNameKey.ItouRiria,
        MemberNameKey.IwamotoRenka,
        MemberNameKey.UmezawaMinami,
        MemberNameKey.OozonoMomoko,
        MemberNameKey.KuboShiori,
        MemberNameKey.SakaguchiTamami,
        MemberNameKey.SatouKaede,
        MemberNameKey.NakamuraReno,
        MemberNameKey.MukaiHazuki,
        MemberNameKey.YamashitaMizuki,
        MemberNameKey.YoshidaAyanoChristie,
        MemberNameKey.YodaYuuki,
        MemberNameKey.EndouSakura,
        MemberNameKey.KakiHaruka,
        MemberNameKey.KakehashiSayaka,
        MemberNameKey.KanagawaSaya,
        MemberNameKey.KitagawaYuri,
        MemberNameKey.ShibataYuna,
        MemberNameKey.SeimiyaRei,
        MemberNameKey.TamuraMayu,
        MemberNameKey.TsutsuiAyame,
        MemberNameKey.HayakawaSeira,
        MemberNameKey.YakuboMio,
        MemberNameKey.KuromiHaruka,
        MemberNameKey.SatouRika,
        MemberNameKey.HayashiRuna,
        MemberNameKey.MatsuoMiyu,
        MemberNameKey.YumikiNao,
        MemberNameKey.IkomaRina,
        MemberNameKey.IchikiRena,
        MemberNameKey.ItouKarin,
        MemberNameKey.EtouMisa,
        MemberNameKey.SaitouChiharu,
        MemberNameKey.SaitouYuuri,
        MemberNameKey.SagaraIori,
        MemberNameKey.SakuraiReika,
        MemberNameKey.NishinoNanase,
        MemberNameKey.NoujouAmi,
        MemberNameKey.WakatsukiYumi,
      ],
    },
  }),
];
