import { SongRaw } from 'server/actors/Songs/models';
import { createSongRaw } from 'server/actors/Songs/raw/creator';
import { SongType } from 'server/actors/Songs/constants/songType';

export const THIRTEENTH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: '今、話したい誰かがいる',
    type: SongType.Title,
    creators: {
      lyrics: ['秋元康'],
      compose: ['Akira Sunset', 'APAZZI'],
      arrange: ['Akira Sunset', 'APAZZI'],
      direct: ['萩原健太郎'],
    },
    center: ['shiraishimai', 'nishinonanase'],
    fukujin: 'row-1-2',
    formations: {
      firstRow: ['etoumisa', 'nishinonanase', 'shiraishimai', 'fukagawamai'],
      secondRow: [
        'saitouasuka',
        'takayamakazumi',
        'hashimotonanami',
        'ikutaerika',
        'akimotomanatsu',
        'hoshinominami',
      ],
      thirdRow: [
        'sakuraireika',
        'wakatsukiyumi',
        'ikomarina',
        'matsumurasayuri',
        'itoumarika',
        'inouesayuri',
      ],
    },
  }),
  createSongRaw({
    title: '嫉妬の権利',
    type: SongType.Under,
    creators: {
      lyrics: ['秋元康'],
      compose: ['丸山真由子'],
      arrange: ['丸山真由子'],
      direct: ['井上強'],
    },
    center: ['horimiona', 'nakamotohimeka'],
    formations: {
      firstRow: ['kitanohinako', 'horimiona', 'nakamotohimeka', 'teradaranze'],
      secondRow: [
        'nakadakana',
        'shinuchimai',
        'kawamuramahiro',
        'nagashimaseira',
        'noujouami',
        'higuchihina',
        'saitouchiharu',
        'saitouyuuri',
      ],
      thirdRow: [
        'kawagohina',
        'watanabemiria',
        'yamazakirena',
        'sasakikotoko',
        'sagaraiori',
        'itoujunna',
        'suzukiayane',
        'itoukarin',
        'wadamaaya',
      ],
    },
  }),
  createSongRaw({
    title: 'ポピパッパパー',
    type: SongType.Selected,
    creators: {
      lyrics: ['秋元康'],
      compose: ['Akira Sunset', 'ha-j'],
      arrange: ['Akira Sunset', 'ha-j'],
      direct: ['丸山健志'],
    },
    center: ['shiraishimai', 'nishinonanase'],
    formations: {
      firstRow: ['etoumisa', 'nishinonanase', 'shiraishimai', 'fukagawamai'],
      secondRow: [
        'saitouasuka',
        'takayamakazumi',
        'hashimotonanami',
        'ikutaerika',
        'akimotomanatsu',
        'hoshinominami',
      ],
      thirdRow: [
        'sakuraireika',
        'wakatsukiyumi',
        'ikomarina',
        'matsumurasayuri',
        'itoumarika',
        'inouesayuri',
      ],
    },
  }),
  createSongRaw({
    title: '大人への近道',
    type: SongType.Unit,
    creators: {
      lyrics: ['秋元康'],
      compose: ['古川貴浩'],
      arrange: ['古川貴浩'],
      direct: ['湯浅弘章'],
    },
    unit: 'サンクエトワール',
    formations: {
      firstRow: [
        'kitanohinako',
        'teradaranze',
        'nakadakana',
        'nakamotohimeka',
        'horimiona',
      ],
    },
  }),
  createSongRaw({
    title: '悲しみの忘れ方',
    type: SongType.Coupling,
    creators: {
      lyrics: ['秋元康'],
      compose: ['近藤圭一'],
      arrange: ['久下真音'],
      direct: ['丸山健志'],
    },
    center: ['ikomarina'],
    formations: {
      firstRow: [
        'ikomarina',
        'akimotomanatsu',
        'ikutaerika',
        'itoumarika',
        'inouesayuri',
        'etoumisa',
        'saitouasuka',
        'saitouyuuri',
        'sakuraireika',
        'shiraishimai',
        'shinuchimai',
        'takayamakazumi',
        'nishinonanase',
        'hashimotonanami',
        'fukagawamai',
        'hoshinominami',
        'matsumurasayuri',
        'wakatsukiyumi',
      ],
    },
    performersType: {
      name: 'selected',
      single: '12',
    },
  }),
  createSongRaw({
    title: '隙間',
    type: SongType.Unit,
    creators: {
      lyrics: ['秋元康'],
      compose: ['Akira Sunset', 'Carlos K.'],
      arrange: ['Akira Sunset', 'Carlos K.'],
    },
    center: ['nishinonanase'],
    formations: {
      firstRow: [
        'itoumarika',
        'inouesayuri',
        'saitouyuuri',
        'sakuraireika',
        'nakadakana',
        'nishinonanase',
        'wakatsukiyumi',
      ],
    },
  }),
];
