import { SongRaw } from "server/actors/Songs/models";
import { createSongRaw } from "server/actors/Songs/raw/creator";
import { FukujinType, SongType } from "server/constants/commons";
import { MemberName } from "server/constants/names";
import { SongTitle } from "server/constants/songs";

export const TWENTIETH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: SongTitle.Synchronicity,
    type: SongType.Title,
    creators: {
      lyrics: ["秋元康"],
      compose: ["シライシ紗トリ"],
      arrange: ["シライシ紗トリ"],
      direct: ["池田一真"],
    },
    center: [MemberName.ShiraishiMai],
    fukujin: FukujinType.RowOneTwo,
    formations: {
      firstRow: [
        MemberName.YamashitaMizuki,
        MemberName.HoriMiona,
        MemberName.IkutaErika,
        MemberName.ShiraishiMai,
        MemberName.NishinoNanase,
        MemberName.SaitouAsuka,
        MemberName.YodaYuuki,
      ],
      secondRow: [
        MemberName.SakuraiReika,
        MemberName.MatsumuraSayuri,
        MemberName.KuboShiori,
        MemberName.IkomaRina,
        MemberName.OozonoMomoko,
        MemberName.EtouMisa,
        MemberName.AkimotoManatsu,
      ],
      thirdRow: [
        MemberName.InoueSayuri,
        MemberName.ShinuchiMai,
        MemberName.TakayamaKazumi,
        MemberName.HoshinoMinami,
        MemberName.WakatsukiYumi,
        MemberName.HiguchiHina,
        MemberName.TeradaRanze,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Atarashiisekai,
    type: SongType.Under,
    creators: {
      lyrics: ["秋元康"],
      compose: ["古川貴浩"],
      arrange: ["古川貴浩"],
      direct: ["横堀光範"],
    },
    center: [MemberName.SuzukiAyane],
    formations: {
      firstRow: [
        MemberName.UmezawaMinami,
        MemberName.WatanabeMiria,
        MemberName.NakadaKana,
        MemberName.SuzukiAyane,
        MemberName.SaitouYuuri,
        MemberName.YamazakiRena,
        MemberName.ItouRiria,
      ],
      secondRow: [
        MemberName.MukaiHazuki,
        MemberName.ItouKarin,
        MemberName.IwamotoRenka,
        MemberName.ItouJunna,
        MemberName.SakaguchiTamami,
        MemberName.SaitouChiharu,
        MemberName.SatouKaede,
      ],
      thirdRow: [
        MemberName.NoujouAmi,
        MemberName.KawagoHina,
        MemberName.YoshidaAyanoChristie,
        MemberName.SasakiKotoko,
        MemberName.NakamuraReno,
        MemberName.WadaMaaya,
        MemberName.SagaraIori,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Against,
    type: SongType.FirstGeneration,
    creators: {
      lyrics: ["秋元康"],
      compose: ["古川貴浩"],
      arrange: ["古川貴浩"],
      direct: ["丸山健志"],
    },
    center: [MemberName.IkomaRina],
    formations: {
      firstRow: [
        MemberName.AkimotoManatsu,
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.InoueSayuri,
        MemberName.EtouMisa,
        MemberName.KawagoHina,
        MemberName.SaitouAsuka,
        MemberName.SaitouChiharu,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.NishinoNanase,
        MemberName.NoujouAmi,
        MemberName.HiguchiHina,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.WakatsukiYumi,
        MemberName.WadaMaaya,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Kumoninarebaii,
    type: SongType.Unit,
    creators: {
      lyrics: ["秋元康"],
      compose: ["丸谷マナブ"],
      arrange: ["丸谷マナブ"],
    },
    unit: "藤桜梨",
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.EtouMisa,
        MemberName.SakuraiReika,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.ScoutMan,
    type: SongType.SecondGeneration,
    creators: {
      lyrics: ["秋元康"],
      compose: ["SaSA"],
      arrange: ["SaSA"],
      direct: ["中村太洸"],
    },
    center: [MemberName.HoriMiona],
    formations: {
      firstRow: [
        MemberName.ItouKarin,
        MemberName.ItouJunna,
        MemberName.SagaraIori,
        MemberName.SasakiKotoko,
        MemberName.ShinuchiMai,
        MemberName.SuzukiAyane,
        MemberName.TeradaRanze,
        MemberName.HoriMiona,
        MemberName.YamazakiRena,
        MemberName.WatanabeMiria,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Tokitokimekimeki,
    type: SongType.ThirdGeneration,
    creators: {
      lyrics: ["秋元康"],
      compose: ["中山聡", "足立優"],
      arrange: ["中山聡", "足立優"],
      direct: ["伊藤衆人"],
    },
    center: [MemberName.IwamotoRenka],
    formations: {
      firstRow: [
        MemberName.ItouRiria,
        MemberName.IwamotoRenka,
        MemberName.UmezawaMinami,
        MemberName.OozonoMomoko,
        MemberName.KuboShiori,
        MemberName.SakaguchiTamami,
        MemberName.SatouKaede,
        MemberName.NakamuraReno,
        MemberName.MukaiHazuki,
        MemberName.YamashitaMizuki,
        MemberName.YoshidaAyanoChristie,
        MemberName.YodaYuuki,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Kotodamahou,
    type: SongType.Unit,
    creators: {
      lyrics: ["秋元康"],
      compose: ["Ryota Saito", "TomoLow"],
      arrange: ["Ryota Saito", "TomoLow"],
    },
    unit: "いもうと坂",
    formations: {
      firstRow: [
        MemberName.OozonoMomoko,
        MemberName.KuboShiori,
        MemberName.YamashitaMizuki,
        MemberName.YodaYuuki,
      ],
    },
  }),
];
