import { SongRaw } from 'server/actors/Songs/models';
import { createSongRaw } from 'server/actors/Songs/raw/creator';
import { SongType } from 'server/actors/Songs/constants/songType';

export const TWENTY_FIRST_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: 'ジコチューで行こう!',
    type: SongType.Title,
    creators: {
      lyrics: ['秋元康'],
      compose: ['ナスカ'],
      arrange: ['野中"まさ"雄一'],
      direct: ['中村太洸'],
    },
    center: ['saitouasuka'],
    fukujin: 'row-1-2',
    formations: {
      firstRow: [
        'ikutaerika',
        'yodayuuki',
        'nishinonanase',
        'saitouasuka',
        'shiraishimai',
        'horimiona',
        'yamashitamizuki',
      ],
      secondRow: [
        'akimotomanatsu',
        'etoumisa',
        'oozonomomoko',
        'umezawaminami',
        'iwamotorenka',
        'matsumurasayuri',
        'sakuraireika',
      ],
      thirdRow: [
        'takayamakazumi',
        'saitouyuuri',
        'wakatsukiyumi',
        'suzukiayane',
        'hoshinominami',
        'shinuchimai',
        'inouesayuri',
      ],
    },
  }),
  createSongRaw({
    title: '三角の空き地',
    type: SongType.Under,
    creators: {
      lyrics: ['秋元康'],
      compose: ['Hiroki'],
      arrange: ['Yasutaka.Ishio'],
      direct: ['月田茂'],
    },
    center: ['nakadakana'],
    formations: {
      firstRow: ['higuchihina', 'nakadakana', 'itouriria'],
      secondRow: [
        'yamazakirena',
        'sakaguchitamami',
        'kitanohinako',
        'teradaranze',
        'watanabemiria',
        'satoukaede',
      ],
      thirdRow: [
        'yoshidaayanochristie',
        'wadamaaya',
        'kawagohina',
        'noujouami',
        'nakamurareno',
        'itoukarin',
        'sasakikotoko',
        'mukaihazuki',
        'itoujunna',
      ],
    },
  }),
  createSongRaw({
    title: '空扉',
    type: SongType.Selected,
    creators: {
      lyrics: ['秋元康'],
      compose: ['FURUTA', 'Dr.Lilcom'],
      arrange: ['Dr.Lilcom'],
      direct: ['伊藤衆人'],
    },
    center: ['umezawaminami'],
    formations: {
      firstRow: [
        'oozonomomoko',
        'yodayuuki',
        'umezawaminami',
        'yamashitamizuki',
        'iwamotorenka',
      ],
      secondRow: [
        'akimotomanatsu',
        'etoumisa',
        'nishinonanase',
        'shiraishimai',
        'matsumurasayuri',
        'ikutaerika',
      ],
      thirdRow: [
        'takayamakazumi',
        'suzukiayane',
        'hoshinominami',
        'shinuchimai',
        'saitouyuuri',
        'inouesayuri',
      ],
    },
  }),
  createSongRaw({
    title: '自分じゃない感じ',
    type: SongType.ThirdGeneration,
    creators: {
      lyrics: ['秋元康'],
      compose: ['ツキダタダシ'],
      arrange: ['ツキダタダシ'],
    },
    center: ['yamashitamizuki'],
    formations: {
      firstRow: ['yodayuuki', 'yamashitamizuki', 'oozonomomoko'],
      secondRow: [
        'umezawaminami',
        'sakaguchitamami',
        'iwamotorenka',
        'nakamurareno',
      ],
      thirdRow: [
        'yoshidaayanochristie',
        'mukaihazuki',
        'itouriria',
        'satoukaede',
      ],
    },
  }),
  createSongRaw({
    title: '心のモノローグ',
    type: SongType.Unit,
    creators: {
      lyrics: ['秋元康'],
      compose: ['シライシ紗トリ'],
      arrange: ['シライシ紗トリ'],
      direct: ['英勉'],
    },
    formations: {
      firstRow: ['shiraishimai', 'nishinonanase'],
    },
  }),
  createSongRaw({
    title: '地球が丸いなら',
    type: SongType.Unit,
    creators: {
      lyrics: ['秋元康'],
      compose: ['山下孝之'],
      arrange: ['山下孝之'],
      direct: ['沖田修一'],
    },
    formations: {
      firstRow: ['oozonomomoko', 'saitouasuka', 'yodayuuki'],
    },
  }),
  createSongRaw({
    title: 'あんなに好きだったのに...',
    type: SongType.Selected,
    creators: {
      lyrics: ['秋元康'],
      compose: ['木下めろん'],
      arrange: ['木下めろん'],
      direct: [],
    },
    center: ['saitouasuka'],
    formations: {
      firstRow: [
        'ikutaerika',
        'yodayuuki',
        'nishinonanase',
        'saitouasuka',
        'shiraishimai',
        'horimiona',
        'yamashitamizuki',
      ],
      secondRow: [
        'akimotomanatsu',
        'etoumisa',
        'oozonomomoko',
        'umezawaminami',
        'iwamotorenka',
        'matsumurasayuri',
        'sakuraireika',
      ],
      thirdRow: [
        'takayamakazumi',
        'saitouyuuri',
        'wakatsukiyumi',
        'suzukiayane',
        'hoshinominami',
        'shinuchimai',
        'inouesayuri',
      ],
    },
  }),
];
