import { createSongRaw } from 'server/actors/Songs/raw/creator';
import { SongRaw } from 'server/actors/Songs/models';

import { SongType } from 'server/actors/Songs/constants/songType';

export const TWENTY_SIXTH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: '僕は僕を好きになる',
    type: SongType.Title,
    creators: {
      lyrics: ['秋元康'],
      compose: ['杉山勝彦'],
      arrange: ['杉山勝彦', '石原剛志'],
      direct: ['奥山大史'],
    },
    center: ['yamashitamizuki'],
    fukujin: 'row-1-2',
    formations: {
      firstRow: [
        'ikutaerika',
        'umezawaminami',
        'yamashitamizuki',
        'kuboshiori',
        'saitouasuka',
      ],
      secondRow: [
        'matsumurasayuri',
        'endousakura',
        'oozonomomoko',
        'horimiona',
        'yodayuuki',
        'kakiharuka',
        'akimotomanatsu',
      ],
      thirdRow: [
        'shinuchimai',
        'seimiyarei',
        'tamuramayu',
        'hoshinominami',
        'tsutsuiayame',
        'iwamotorenka',
        'takayamakazumi',
      ],
    },
  }),
  createSongRaw({
    title: '冷たい水の中',
    type: SongType.Solo,
    creators: {
      lyrics: ['秋元康'],
      compose: ['山口寛雄'],
      arrange: ['山口寛雄'],
      direct: ['山戸結希'],
    },
    solo: 'horimiona',
  }),
  createSongRaw({
    title: 'Out of the blue',
    type: SongType.FourthGeneration,
    creators: {
      lyrics: ['秋元康'],
      compose: ['youth case'],
      arrange: ['石塚知生'],
      direct: ['N2B'],
    },
    center: ['hayakawaseira'],
    formations: {
      firstRow: ['kakiharuka', 'hayakawaseira', 'tamuramayu'],
      secondRow: [
        'seimiyarei',
        'tsutsuiayame',
        'kanagawasaya',
        'endousakura',
        'kakehashisayaka',
        'satourika',
      ],
      thirdRow: [
        'matsuomiyu',
        'yakubomio',
        'kuromiharuka',
        'shibatayuna',
        'hayashiruna',
        'kitagawayuri',
        'yumikinao',
      ],
    },
  }),
  createSongRaw({
    title: '口ほどにもないKISS',
    type: SongType.Under,
    creators: {
      lyrics: ['秋元康'],
      compose: ['中村泰輔'],
      arrange: ['中村泰輔'],
      direct: ['頃安祐良'],
    },
    center: ['sakaguchitamami'],
    formations: {
      firstRow: ['suzukiayane', 'sakaguchitamami', 'kitanohinako'],
      secondRow: [
        'yamazakirena',
        'watanabemiria',
        'higuchihina',
        'teradaranze',
        'itouriria',
      ],
      thirdRow: [
        'itoujunna',
        'satoukaede',
        'mukaihazuki',
        'wadamaaya',
        'yoshidaayanochristie',
        'nakamurareno',
      ],
    },
  }),
  createSongRaw({
    title: '明日がある理由',
    type: SongType.Coupling,
    creators: {
      lyrics: ['秋元康'],
      compose: ['YU-JIN'],
      arrange: ['YU-JIN'],
    },
    center: ['iwamotorenka'],
    formations: {
      firstRow: ['tsutsuiayame', 'iwamotorenka', 'endousakura'],
      secondRow: [
        'umezawaminami',
        'yamashitamizuki',
        'kuboshiori',
        'kakiharuka',
        'yodayuuki',
        'oozonomomoko',
      ],
      thirdRow: [
        'shinuchimai',
        'akimotomanatsu',
        'hoshinominami',
        'ikutaerika',
        'saitouasuka',
        'horimiona',
        'kitanohinako',
        'takayamakazumi',
        'matsumurasayuri',
      ],
    },
  }),
  createSongRaw({
    title: 'Wilderness world',
    type: SongType.Coupling,
    creators: {
      lyrics: ['秋元康'],
      compose: ['youth case'],
      arrange: ['youth case', '城戸紘志'],
      direct: ['東市篤憲'],
    },
    center: ['saitouasuka'],
    formations: {
      firstRow: [
        'kakiharuka',
        'yodayuuki',
        'saitouasuka',
        'yamashitamizuki',
        'matsumurasayuri',
      ],
      secondRow: [
        'akimotomanatsu',
        'oozonomomoko',
        'kuboshiori',
        'endousakura',
        'ikutaerika',
        'horimiona',
        'umezawaminami',
      ],
      thirdRow: [
        'tamuramayu',
        'hoshinominami',
        'iwamotorenka',
        'tsutsuiayame',
        'seimiyarei',
        'takayamakazumi',
        'shinuchimai',
      ],
    },
  }),
  createSongRaw({
    title: '友情ピアス',
    type: SongType.Unit,
    creators: {
      lyrics: ['秋元康'],
      compose: ['カワノミチオ'],
      arrange: ['カワノミチオ'],
      direct: ['高野寛地'],
    },
    formations: {
      firstRow: ['endousakura', 'oozonomomoko'],
    },
  }),
];
