import { SongRaw } from 'server/actors/Songs/models';
import { createSongRaw } from 'server/actors/Songs/raw/creator';

export const TWENTY_EIGHTH_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: '君に叱られた',
    type: 'title',
    center: ['kakiharuka'],
    fukujin: 'row-1-2',
    formations: {
      firstRow: [
        'endousakura',
        'yodayuuki',
        'kakiharuka',
        'saitouasuka',
        'yamashitamizuki',
      ],
      secondRow: [
        'tsutsuiayame',
        'umezawaminami',
        'hoshinominami',
        'takayamakazumi',
        'ikutaerika',
        'kuboshiori',
        'akimotomanatsu',
      ],
      thirdRow: [
        'higuchihina',
        'hayakawaseira',
        'seimiyarei',
        'kitanohinako',
        'iwamotorenka',
        'suzukiayane',
        'tamuramayu',
        'shinuchimai',
        'kakehashisayaka',
      ],
    },
    creators: {
      lyrics: ['秋元康'],
      compose: ['youth case'],
      direct: ['横堀光範'],
    },
  }),
  createSongRaw({
    title: 'やさしいだけなら',
    type: 'unit',
    formations: {
      firstRow: ['ikutaerika', 'kakiharuka', 'kuboshiori'],
    },
  }),
  createSongRaw({
    title: 'マシンガンレイン',
    type: 'under',
    center: ['teradaranze'],
    formations: {
      firstRow: [
        'yumikinao',
        'shibatayuna',
        'teradaranze',
        'nakamurareno',
        'yamazakirena',
      ],
      secondRow: [
        'matsuomiyu',
        'hayashiruna',
        'sakaguchitamami',
        'kanagawasaya',
        'satourika',
        'satoukaede',
      ],
      thirdRow: [
        'itouriria',
        'kuromiharuka',
        'yakubomio',
        'wadamaaya',
        'kitagawayuri',
        'yoshidaayanochristie',
        'mukaihazuki',
      ],
    },
    creators: {
      lyrics: ['秋元康'],
      direct: ['今原電気'],
    },
  }),
  createSongRaw({
    title: 'もしも心が透明なら',
    type: 'unit',
    formations: {
      firstRow: [
        'umezawaminami',
        'nakamurareno',
        'hayakawaseira',
        'matsuomiyu',
      ],
    },
  }),
  createSongRaw({
    title: '私の色',
    type: 'solo',
    solo: 'takayamakazumi',
    creators: {
      lyrics: ['秋元康'],
      direct: ['頃安祐良'],
    },
  }),
  createSongRaw({
    title: '泥だらけ',
    type: 'unit',
    formations: {
      firstRow: [
        'endousakura',
        'kuboshiori',
        'saitouasuka',
        'tsutsuiayame',
        'yamashitamizuki',
        'wadamaaya',
      ],
    },
  }),
  createSongRaw({
    title: '他人のそら似',
    type: 'none',
    formations: {
      firstRow: [
        'akimotomanatsu',
        'ikutaerika',
        'itouriria',
        'iwamotorenka',
        'umezawaminami',
        'oozonomomoko',
        'kitanohinako',
        'kuboshiori',
        'saitouasuka',
        'sakaguchitamami',
        'satoukaede',
        'shinuchimai',
        'suzukiayane',
        'takayamakazumi',
        'teradaranze',
        'nakamurareno',
        'higuchihina',
        'hoshinominami',
        'mukaihazuki',
        'yamazakirena',
        'yamashitamizuki',
        'yoshidaayanochristie',
        'yodayuuki',
        'wadamaaya',
        'endousakura',
        'kakiharuka',
        'kakehashisayaka',
        'kanagawasaya',
        'kitagawayuri',
        'kuromiharuka',
        'satourika',
        'shibatayuna',
        'seimiyarei',
        'tamuramayu',
        'tsutsuiayame',
        'hayakawaseira',
        'hayashiruna',
        'matsuomiyu',
        'yakubomio',
        'yumikinao',
      ],
    },
  }),
];
