import { RawSingle } from "../models/ISingle";
import { CdType } from "../utils/constants";
import { MemberName } from "./constants/names";
import { Songs } from "./constants/titles";

const hogoshoku: RawSingle = {
  title: "しあわせの保護色",
  number: "25",
  release: "2020-03-25",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["しあわせの保護色"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["サヨナラ Stay with me"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["じゃあね。"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["アナスターシャ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["毎日がBrand new day"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["I see…"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["ファンタスティック三色パン"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouJunna,
    MemberName.ItouRiria,
    MemberName.SakaguchiTamami,
    MemberName.SasakiKotoko,
    MemberName.SatouKaede,
    MemberName.SuzukiAyane,
    MemberName.TeradaRanze,
    MemberName.NakamuraReno,
    MemberName.MukaiHazuki,
    MemberName.YamazakiRena,
    MemberName.YoshidaAyanoChristie,
    MemberName.WatanabeMiria,
  ],
  behindPerformers: {
    trainees: [
      MemberName.KakehashiSayaka,
      MemberName.KanagawaSaya,
      MemberName.KitagawaYuri,
      MemberName.ShibataYuna,
      MemberName.SeimiyaRei,
      MemberName.TamuraMayu,
      MemberName.HayakawaSeira,
      MemberName.YakuboMio,
      MemberName.TsutsuiAyame,
    ],
    skips: [],
  },
};

const yoakemade: RawSingle = {
  title: "夜明けまで強がらなくてもいい",
  number: "24",
  release: "2019-09-04",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["夜明けまで強がらなくてもいい"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["僕のこと、知ってる?"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["路面電車の街"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["図書室の君へ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["時々 思い出してください"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["～Do my best～じゃ意味はない"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["僕の思い込み"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouJunna,
    MemberName.ItouRiria,
    MemberName.IwamotoRenka,
    MemberName.SakaguchiTamami,
    MemberName.SasakiKotoko,
    MemberName.SatouKaede,
    MemberName.SuzukiAyane,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.NakamuraReno,
    MemberName.HiguchiHina,
    MemberName.MukaiHazuki,
    MemberName.YamazakiRena,
    MemberName.YoshidaAyanoChristie,
    MemberName.WatanabeMiria,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.KakehashiSayaka,
      MemberName.KanagawaSaya,
      MemberName.KitagawaYuri,
      MemberName.ShibataYuna,
      MemberName.SeimiyaRei,
      MemberName.TamuraMayu,
      MemberName.HayakawaSeira,
      MemberName.YakuboMio,
    ],
    skips: [MemberName.InoueSayuri, MemberName.OozonoMomoko],
  },
};

const singout: RawSingle = {
  title: "Sing Out!",
  number: "23",
  release: "2019-05-29",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["Sing Out!"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["滑走路"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["のような存在"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["Am I Loving?"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["平行線"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["4番目の光"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["曖昧"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouJunna,
    MemberName.SasakiKotoko,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.NakamuraReno,
    MemberName.HiguchiHina,
    MemberName.MukaiHazuki,
    MemberName.YamazakiRena,
    MemberName.YoshidaAyanoChristie,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.EndouSakura,
      MemberName.KakiHaruka,
      MemberName.KakehashiSayaka,
      MemberName.KanagawaSaya,
      MemberName.KitagawaYuri,
      MemberName.ShibataYuna,
      MemberName.SeimiyaRei,
      MemberName.TamuraMayu,
      MemberName.TsutsuiAyame,
      MemberName.HayakawaSeira,
      MemberName.YakuboMio,
    ],
    skips: [MemberName.YamashitaMizuki],
  },
};

const kaerimichi: RawSingle = {
  title: "帰り道は遠回りしたくなる",
  number: "22",
  release: "2018-11-14",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["帰り道は遠回りしたくなる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["キャラバンは眠らない"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["つづく"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["日常"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["告白の順番"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["ショパンの嘘つき"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["知りたいこと"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SuzukiAyane,
    MemberName.HiguchiHina,
    MemberName.KitanoHinako,
    MemberName.TeradaRanze,
    MemberName.IwamotoRenka,
    MemberName.SakaguchiTamami,
    MemberName.YamazakiRena,
    MemberName.KuboShiori,
    MemberName.NakadaKana,
    MemberName.WatanabeMiria,
    MemberName.MukaiHazuki,
    MemberName.ItouJunna,
    MemberName.WadaMaaya,
    MemberName.NakamuraReno,
    MemberName.KawagoHina,
    MemberName.ItouKarin,
    MemberName.SasakiKotoko,
    MemberName.YoshidaAyanoChristie,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const jikochu: RawSingle = {
  title: "ジコチューで行こう!",
  number: "21",
  release: "2018-08-08",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["ジコチューで行こう!"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["空扉"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["三角の空き地"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["自分じゃない感じ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["心のモノローグ"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["地球が丸いなら"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["あんなに好きだったのに..."].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.NakadaKana,
    MemberName.ItouRiria,
    MemberName.YamazakiRena,
    MemberName.SakaguchiTamami,
    MemberName.KitanoHinako,
    MemberName.TeradaRanze,
    MemberName.WatanabeMiria,
    MemberName.SatouKaede,
    MemberName.YoshidaAyanoChristie,
    MemberName.WadaMaaya,
    MemberName.KawagoHina,
    MemberName.NoujouAmi,
    MemberName.NakamuraReno,
    MemberName.ItouKarin,
    MemberName.SasakiKotoko,
    MemberName.MukaiHazuki,
    MemberName.ItouJunna,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.KuboShiori],
  },
};

const syncronicity: RawSingle = {
  title: "シンクロニシティ",
  number: "20",
  release: "2018-04-25",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["シンクロニシティ"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["Against"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["雲になればいい"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["新しい世界"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["スカウトマン"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["トキトキメキメキ"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["言霊砲"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.UmezawaMinami,
    MemberName.WatanabeMiria,
    MemberName.NakadaKana,
    MemberName.SuzukiAyane,
    MemberName.SaitouYuuri,
    MemberName.YamazakiRena,
    MemberName.ItouRiria,
    MemberName.MukaiHazuki,
    MemberName.ItouKarin,
    MemberName.IwamotoRenka,
    MemberName.ItouJunna,
    MemberName.SakaguchiTamami,
    MemberName.SaitouChiharu,
    MemberName.SatouKaede,
    MemberName.NoujouAmi,
    MemberName.KawagoHina,
    MemberName.YoshidaAyanoChristie,
    MemberName.SasakiKotoko,
    MemberName.NakamuraReno,
    MemberName.WadaMaaya,
    MemberName.SagaraIori,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.KitanoHinako],
  },
};

const itsukadekirukara: RawSingle = {
  title: "いつかできるから今日できる",
  number: "19",
  release: "2017-10-11",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["いつかできるから今日できる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["不眠症"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["まあいいか?"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["失恋お掃除人"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["My rule"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["僕の衝動"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["新しい花粉 〜ミュージカル「見知らぬ世界」より〜"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.WatanabeMiria,
    MemberName.HiguchiHina,
    MemberName.TeradaRanze,
    MemberName.NoujouAmi,
    MemberName.SuzukiAyane,
    MemberName.YamazakiRena,
    MemberName.SaitouChiharu,
    MemberName.SagaraIori,
    MemberName.SasakiKotoko,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.WadaMaaya,
    MemberName.ItouJunna,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouRiria,
      MemberName.IwamotoRenka,
      MemberName.UmezawaMinami,
      MemberName.OozonoMomoko,
      MemberName.KuboShiori,
      MemberName.SakaguchiTamami,
      MemberName.SatouKaede,
      MemberName.NakamuraReno,
      MemberName.MukaiHazuki,
      MemberName.YamashitaMizuki,
      MemberName.YoshidaAyanoChristie,
      MemberName.YodaYuuki,
    ],
    skips: [],
  },
};

const nigemizu: RawSingle = {
  title: "逃げ水",
  number: "18",
  release: "2017-08-09",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["逃げ水"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["女は一人じゃ眠れない"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["ひと夏の長さより…"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["泣いたっていいじゃないか?"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["アンダー"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["ライブ神"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["未来の答え"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.WatanabeMiria,
    MemberName.NakamotoHimeka,
    MemberName.KitanoHinako,
    MemberName.TeradaRanze,
    MemberName.SaitouYuuri,
    MemberName.NakadaKana,
    MemberName.YamazakiRena,
    MemberName.SuzukiAyane,
    MemberName.ItouKarin,
    MemberName.ItouJunna,
    MemberName.SaitouChiharu,
    MemberName.NoujouAmi,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.SasakiKotoko,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouRiria,
      MemberName.IwamotoRenka,
      MemberName.UmezawaMinami,
      MemberName.KuboShiori,
      MemberName.SakaguchiTamami,
      MemberName.SatouKaede,
      MemberName.NakamuraReno,
      MemberName.MukaiHazuki,
      MemberName.YamashitaMizuki,
      MemberName.YoshidaAyanoChristie,
    ],
    skips: [],
  },
};

const influencer: RawSingle = {
  title: "インフルエンサー",
  number: "17",
  release: "2017-03-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["インフルエンサー"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["人生を考えたくなる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["意外BREAK"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["Another Ghost"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["風船は生きている"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["三番目の風"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["当たり障りのない話"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.YamazakiRena,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.SaitouChiharu,
    MemberName.ItouKarin,
    MemberName.NoujouAmi,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.SasakiKotoko,
    MemberName.WadaMaaya,
    MemberName.ItouJunna,
    MemberName.KawamuraMahiro,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouRiria,
      MemberName.IwamotoRenka,
      MemberName.UmezawaMinami,
      MemberName.OozonoMomoko,
      MemberName.KuboShiori,
      MemberName.SakaguchiTamami,
      MemberName.SatouKaede,
      MemberName.NakamuraReno,
      MemberName.MukaiHazuki,
      MemberName.YamashitaMizuki,
      MemberName.YoshidaAyanoChristie,
      MemberName.YodaYuuki,
    ],
    skips: [MemberName.NakamotoHimeka],
  },
};

const sayonaranoimi: RawSingle = {
  title: "サヨナラの意味",
  number: "16",
  release: "2016-11-09",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["サヨナラの意味"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["孤独な青空"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["あの教室"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["ブランコ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["2度目のキスから"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["君に贈る花がない"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["ないものねだり"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KawamuraMahiro,
    MemberName.HiguchiHina,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.SaitouYuuri,
    MemberName.YamazakiRena,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.SaitouChiharu,
    MemberName.ItouJunna,
    MemberName.WadaMaaya,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.SasakiKotoko,
    MemberName.SagaraIori,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const hadashidesummer: RawSingle = {
  title: "裸足でSummer",
  number: "15",
  release: "2016-07-27",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["裸足でSummer"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["僕だけの光"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["オフショアガール"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["命の真実 ミュージカル「林檎売りとカメムシ」"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["白米様"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["シークレットグラフィティー"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["行くあてのない僕たち"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.TeradaRanze,
    MemberName.ItouMarika,
    MemberName.HiguchiHina,
    MemberName.InoueSayuri,
    MemberName.WatanabeMiria,
    MemberName.SaitouChiharu,
    MemberName.SaitouYuuri,
    MemberName.ShinuchiMai,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.KawamuraMahiro,
    MemberName.YamazakiRena,
    MemberName.ItouJunna,
    MemberName.KawagoHina,
    MemberName.SuzukiAyane,
    MemberName.WadaMaaya,
    MemberName.SagaraIori,
    MemberName.SasakiKotoko,
    MemberName.ItouKarin,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const harujion: RawSingle = {
  title: "ハルジオンが咲く頃",
  number: "14",
  release: "2016-03-23",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["ハルジオンが咲く頃"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: Songs["遥かなるブータン"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: Songs["強がる蕾"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["急斜面"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["釣り堀"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["不等号"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: Songs["憂鬱と風船ガム"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouYuuri,
    MemberName.TeradaRanze,
    MemberName.NakamotoHimeka,
    MemberName.KitanoHinako,
    MemberName.HiguchiHina,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.NakadaKana,
    MemberName.ShinuchiMai,
    MemberName.NoujouAmi,
    MemberName.SaitouChiharu,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.YamazakiRena,
    MemberName.SasakiKotoko,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.WadaMaaya,
    MemberName.ItouJunna,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const hanashitaidarekagairu: RawSingle = {
  title: "今、話したい誰かがいる",
  number: "13",
  release: "2015-10-28",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["今、話したい誰かがいる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["嫉妬の権利"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["ポピパッパパー"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["大人への近道"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["悲しみの忘れ方"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["隙間"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KitanoHinako,
    MemberName.HoriMiona,
    MemberName.NakamotoHimeka,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.ShinuchiMai,
    MemberName.KawamuraMahiro,
    MemberName.NagashimaSeira,
    MemberName.NoujouAmi,
    MemberName.HiguchiHina,
    MemberName.SaitouChiharu,
    MemberName.SaitouYuuri,
    MemberName.KawagoHina,
    MemberName.WatanabeMiria,
    MemberName.YamazakiRena,
    MemberName.SasakiKotoko,
    MemberName.SagaraIori,
    MemberName.ItouJunna,
    MemberName.SuzukiAyane,
    MemberName.ItouKarin,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const taiyoknock: RawSingle = {
  title: "太陽ノック",
  number: "12",
  release: "2015-07-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["太陽ノック"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T, CdType.L],
    },
    {
      number: 2,
      title: Songs["もう少しの夢"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T, CdType.L],
    },
    {
      number: 3,
      title: Songs["魚たちのLOVE SONG"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["無表情"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["別れ際、もっと好きになる"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["羽根の記憶"].title,
      inCdType: [CdType.T],
    },
    {
      number: 7,
      title: Songs["制服を脱いでサヨナラを…"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KawamuraMahiro,
    MemberName.KitanoHinako,
    MemberName.HoriMiona,
    MemberName.NakamotoHimeka,
    MemberName.NakadaKana,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.NagashimaSeira,
    MemberName.NoujouAmi,
    MemberName.SaitouChiharu,
    MemberName.WadaMaaya,
    MemberName.SasakiKotoko,
    MemberName.TeradaRanze,
    MemberName.ItouKarin,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.ItouJunna,
    MemberName.HiguchiHina,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.YamazakiRena],
  },
};

const inochihautsukushii: RawSingle = {
  title: "命は美しい",
  number: "11",
  release: "2015-03-18",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["命は美しい"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["あらかじめ語られるロマンス"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["立ち直り中"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["ごめんね ずっと…"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["君は僕と会わない方がよかったのかな"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["ボーダー"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouYuuri,
    MemberName.NakamotoHimeka,
    MemberName.InoueSayuri,
    MemberName.NoujouAmi,
    MemberName.NagashimaSeira,
    MemberName.NakadaKana,
    MemberName.ShinuchiMai,
    MemberName.KawamuraMahiro,
    MemberName.KitanoHinako,
    MemberName.KawagoHina,
    MemberName.HiguchiHina,
    MemberName.ItouKarin,
    MemberName.WadaMaaya,
    MemberName.SaitouChiharu,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouJunna,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
    ],
    skips: [],
  },
};

const nandomenoaozoraka: RawSingle = {
  title: "何度目の青空か?",
  number: "10",
  release: "2014-10-08",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["何度目の青空か?"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["遠回りの愛情"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["転がった鐘を鳴らせ!"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["私、起きる。"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["あの日 僕は咄嗟に嘘をついた"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["Tender days"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouAsuka,
    MemberName.InoueSayuri,
    MemberName.ItouMarika,
    MemberName.NagashimaSeira,
    MemberName.NakamotoHimeka,
    MemberName.SaitouYuuri,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.KawamuraMahiro,
    MemberName.WadaMaaya,
    MemberName.HiguchiHina,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.HatanakaSeira,
    MemberName.KitanoHinako,
    MemberName.YamatoRina,
    MemberName.ShinuchiMai,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouJunna,
      MemberName.SagaraIori,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
    ],
    skips: [],
  },
};

const natsunofreeandeasy: RawSingle = {
  title: "夏のFree&Easy",
  number: "9",
  release: "2014-07-09",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["夏のFree&Easy"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["何もできずにそばにいる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["その先の出口!"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["無口なライオン"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["ここにいる理由"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["僕が行かなきゃ誰が行くんだ?"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KawagoHina,
    MemberName.SaitouAsuka,
    MemberName.ItouMarika,
    MemberName.HiguchiHina,
    MemberName.WadaMaaya,
    MemberName.NagashimaSeira,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.NakamotoHimeka,
    MemberName.KawamuraMahiro,
    MemberName.SaitouChiharu,
    MemberName.KitanoHinako,
    MemberName.HatanakaSeira,
    MemberName.ItouNene,
    MemberName.IchikiRena,
    MemberName.ShinuchiMai,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouKarin,
      MemberName.ItouJunna,
      MemberName.SagaraIori,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
      MemberName.YonetokuKyouka,
      MemberName.YadaRisako,
    ],
    skips: [MemberName.IkutaErika],
  },
};

const kizuitarakataomoi: RawSingle = {
  title: "気づいたら片想い",
  number: "8",
  release: "2014-04-02",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["気づいたら片想い"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["ロマンスのスタート"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["吐息のメソッド"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["孤独兄弟"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["生まれたままで"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["ダンケシェーン"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.InoueSayuri,
    MemberName.SaitouAsuka,
    MemberName.ItouMarika,
    MemberName.HoshinoMinami,
    MemberName.SaitouYuuri,
    MemberName.NagashimaSeira,
    MemberName.NakadaKana,
    MemberName.EtouMisa,
    MemberName.KawagoHina,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
    MemberName.ItouNene,
    MemberName.IchikiRena,
    MemberName.ShinuchiMai,
    MemberName.HatanakaSeira,
    MemberName.YamatoRina,
    MemberName.NoujouAmi,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouKarin,
      MemberName.ItouJunna,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
      MemberName.YonetokuKyouka,
      MemberName.YadaRisako,
    ],
    skips: [MemberName.SagaraIori],
  },
};

const valletta: RawSingle = {
  title: "バレッタ",
  number: "7",
  release: "2013-11-27",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["バレッタ"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["月の大きさ"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["私のために 誰かのために"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["そんなバカな…"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["初恋の人を今でも"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["やさしさとは"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.InoueSayuri,
    MemberName.HoshinoMinami,
    MemberName.SaitouYuuri,
    MemberName.NoujouAmi,
    MemberName.HiguchiHina,
    MemberName.NakadaKana,
    MemberName.NagashimaSeira,
    MemberName.KawamuraMahiro,
    MemberName.SaitouChiharu,
    MemberName.HatanakaSeira,
    MemberName.YamatoRina,
    MemberName.ItouNene,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouKarin,
      MemberName.ItouJunna,
      MemberName.KitanoHinako,
      MemberName.SasakiKotoko,
      MemberName.ShinuchiMai,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
      MemberName.YonetokuKyouka,
      MemberName.YadaRisako,
      MemberName.NishikawaNanami,
    ],
    skips: [MemberName.IchikiRena, MemberName.SagaraIori],
  },
};

const girlsrule: RawSingle = {
  title: "ガールズルール",
  number: "6",
  release: "2013-07-03",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["ガールズルール"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["世界で一番 孤独なLover"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["コウモリよ"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["扇風機"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["他の星から"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["人間という楽器"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.SaitouAsuka,
    MemberName.NakamotoHimeka,
    MemberName.NoujouAmi,
    MemberName.EtouMisa,
    MemberName.KawamuraMahiro,
    MemberName.ItouNene,
    MemberName.NagashimaSeira,
    MemberName.SaitouChiharu,
    MemberName.IchikiRena,
    MemberName.YamatoRina,
    MemberName.KawagoHina,
    MemberName.WadaMaaya,
    MemberName.KashiwaYukina,
    MemberName.HatanakaSeira,
    MemberName.MiyazawaSeira,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const kiminonahakibo: RawSingle = {
  title: "君の名は希望",
  number: "5",
  release: "2013-03-31",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["君の名は希望"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["シャキイズム"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["ロマンティックいか焼き"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["13日の金曜日"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["でこぴん"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["サイコキネシスの可能性"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouMarika,
    MemberName.SaitouYuuri,
    MemberName.SaitouAsuka,
    MemberName.KawamuraMahiro,
    MemberName.EtouMisa,
    MemberName.NoujouAmi,
    MemberName.IchikiRena,
    MemberName.YamatoRina,
    MemberName.WadaMaaya,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
    MemberName.KashiwaYukina,
    MemberName.AndouMikumo,
    MemberName.HatanakaSeira,
    MemberName.HiguchiHina,
    MemberName.KawagoHina,
    MemberName.MiyazawaSeira,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const seifukunomannequin: RawSingle = {
  title: "制服のマネキン",
  number: "4",
  release: "2012-12-19",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["制服のマネキン"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["指望遠鏡"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["やさしさなら間に合ってる"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["ここじゃないどこか"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["春のメロディー"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["渋谷ブルース"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouYuuri,
    MemberName.NakadaKana,
    MemberName.EtouMisa,
    MemberName.ItouMarika,
    MemberName.KawagoHina,
    MemberName.HiguchiHina,
    MemberName.ItouNene,
    MemberName.KawamuraMahiro,
    MemberName.NakamotoHimeka,
    MemberName.HatanakaSeira,
    MemberName.NagashimaSeira,
    MemberName.MiyazawaSeira,
    MemberName.YamatoRina,
    MemberName.AndouMikumo,
    MemberName.WadaMaaya,
    MemberName.SaitouChiharu,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.KashiwaYukina],
  },
};

const hashirebicycle: RawSingle = {
  title: "走れ!Bicycle",
  number: "3",
  release: "2012-08-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["走れ!Bicycle"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["せっかちなかたつむり"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["涙がまだ悲しみだった頃"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["人はなぜ走るのか?"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["音が出ないギター"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["海流の島よ"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.ItouNene,
    MemberName.SaitouAsuka,
    MemberName.EtouMisa,
    MemberName.NoujouAmi,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.KashiwaYukina,
    MemberName.YamatoRina,
    MemberName.NagashimaSeira,
    MemberName.MiyazawaSeira,
    MemberName.AndouMikumo,
    MemberName.HatanakaSeira,
    MemberName.IwaseYumiko,
    MemberName.WadaMaaya,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.AkimotoManatsu],
  },
};

const oideshampoo: RawSingle = {
  title: "おいでシャンプー",
  number: "2",
  release: "2012-05-02",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["おいでシャンプー"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["心の薬"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["偶然を言い訳にして"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["水玉模様"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["狼に口笛を"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["ハウス!"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.FukagawaMai,
    MemberName.ItouMarika,
    MemberName.WakatsukiYumi,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.SaitouChiharu,
    MemberName.NagashimaSeira,
    MemberName.EtouMisa,
    MemberName.ItouNene,
    MemberName.SaitouAsuka,
    MemberName.NakamotoHimeka,
    MemberName.HiguchiHina,
    MemberName.KashiwaYukina,
    MemberName.AndouMikumo,
    MemberName.YamatoRina,
    MemberName.NoujouAmi,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.AkimotoManatsu],
  },
};

const gurugurucurtain: RawSingle = {
  title: "ぐるぐるカーテン",
  number: "1",
  release: "2012-02-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: Songs["ぐるぐるカーテン"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: Songs["左胸の勇気"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: Songs["乃木坂の詩"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: Songs["会いたかったかもしれない"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: Songs["失いたくないから"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: Songs["白い雲にのって"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.AndouMikumo,
    MemberName.IwaseYumiko,
    MemberName.ItouNene,
    MemberName.HatanakaSeira,
    MemberName.ItouMarika,
    MemberName.WadaMaaya,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
    MemberName.YamatoRina,
    MemberName.NagashimaSeira,
    MemberName.HiguchiHina,
    MemberName.KawagoHina,
    MemberName.WakatsukiYumi,
    MemberName.KashiwaYukina,
    MemberName.EtouMisa,
    MemberName.FukagawaMai,
    MemberName.MiyazawaSeira,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.AkimotoManatsu],
  },
};

export const rawSingles: RawSingle[] = [
  hogoshoku,
  yoakemade,
  singout,
  kaerimichi,
  jikochu,
  syncronicity,
  itsukadekirukara,
  nigemizu,
  influencer,
  sayonaranoimi,
  hadashidesummer,
  harujion,
  hanashitaidarekagairu,
  taiyoknock,
  inochihautsukushii,
  nandomenoaozoraka,
  natsunofreeandeasy,
  kizuitarakataomoi,
  valletta,
  girlsrule,
  kiminonahakibo,
  seifukunomannequin,
  hashirebicycle,
  oideshampoo,
  gurugurucurtain,
];
