import { SingleRaw, SinglesRawArray } from "server/actors/Singles/models";
import { CdType } from "server/constants/commons";
import { SONGS } from "server/constants/songs";
import { MemberName } from "server/constants/names";

const hogoshoku: SingleRaw = {
  title: "しあわせの保護色",
  number: "25",
  release: "2020-03-25",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["しあわせの保護色"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["サヨナラ Stay with me"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["じゃあね。"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["アナスターシャ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["毎日がBrand new day"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["I see…"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["ファンタスティック三色パン"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouJunna,
    MemberName.ItouRiria,
    MemberName.SakaguchiTamami,
    MemberName.SasakiKotoko,
    MemberName.SatouKaede,
    MemberName.SuzukiAyane,
    MemberName.TeradaRanze,
    MemberName.NakamuraReno,
    MemberName.MukaiHazuki,
    MemberName.YamazakiRena,
    MemberName.YoshidaAyanoChristie,
    MemberName.WatanabeMiria,
  ],
  behindPerformers: {
    trainees: [
      MemberName.KakehashiSayaka,
      MemberName.KanagawaSaya,
      MemberName.KitagawaYuri,
      MemberName.ShibataYuna,
      MemberName.SeimiyaRei,
      MemberName.TamuraMayu,
      MemberName.HayakawaSeira,
      MemberName.YakuboMio,
      MemberName.TsutsuiAyame,
    ],
    skips: [],
  },
};

const yoakemade: SingleRaw = {
  title: "夜明けまで強がらなくてもいい",
  number: "24",
  release: "2019-09-04",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["夜明けまで強がらなくてもいい"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["僕のこと、知ってる?"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["路面電車の街"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["図書室の君へ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["時々 思い出してください"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["～Do my best～じゃ意味はない"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["僕の思い込み"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouJunna,
    MemberName.ItouRiria,
    MemberName.IwamotoRenka,
    MemberName.SakaguchiTamami,
    MemberName.SasakiKotoko,
    MemberName.SatouKaede,
    MemberName.SuzukiAyane,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.NakamuraReno,
    MemberName.HiguchiHina,
    MemberName.MukaiHazuki,
    MemberName.YamazakiRena,
    MemberName.YoshidaAyanoChristie,
    MemberName.WatanabeMiria,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.KakehashiSayaka,
      MemberName.KanagawaSaya,
      MemberName.KitagawaYuri,
      MemberName.ShibataYuna,
      MemberName.SeimiyaRei,
      MemberName.TamuraMayu,
      MemberName.HayakawaSeira,
      MemberName.YakuboMio,
    ],
    skips: [MemberName.InoueSayuri, MemberName.OozonoMomoko],
  },
};

const singout: SingleRaw = {
  title: "Sing Out!",
  number: "23",
  release: "2019-05-29",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["Sing Out!"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["滑走路"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["のような存在"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["Am I Loving?"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["平行線"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["4番目の光"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["曖昧"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouJunna,
    MemberName.SasakiKotoko,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.NakamuraReno,
    MemberName.HiguchiHina,
    MemberName.MukaiHazuki,
    MemberName.YamazakiRena,
    MemberName.YoshidaAyanoChristie,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.EndouSakura,
      MemberName.KakiHaruka,
      MemberName.KakehashiSayaka,
      MemberName.KanagawaSaya,
      MemberName.KitagawaYuri,
      MemberName.ShibataYuna,
      MemberName.SeimiyaRei,
      MemberName.TamuraMayu,
      MemberName.TsutsuiAyame,
      MemberName.HayakawaSeira,
      MemberName.YakuboMio,
    ],
    skips: [MemberName.YamashitaMizuki],
  },
};

const kaerimichi: SingleRaw = {
  title: "帰り道は遠回りしたくなる",
  number: "22",
  release: "2018-11-14",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["帰り道は遠回りしたくなる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["キャラバンは眠らない"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["つづく"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["日常"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["告白の順番"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["ショパンの嘘つき"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["知りたいこと"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SuzukiAyane,
    MemberName.HiguchiHina,
    MemberName.KitanoHinako,
    MemberName.TeradaRanze,
    MemberName.IwamotoRenka,
    MemberName.SakaguchiTamami,
    MemberName.YamazakiRena,
    MemberName.KuboShiori,
    MemberName.NakadaKana,
    MemberName.WatanabeMiria,
    MemberName.MukaiHazuki,
    MemberName.ItouJunna,
    MemberName.WadaMaaya,
    MemberName.NakamuraReno,
    MemberName.KawagoHina,
    MemberName.ItouKarin,
    MemberName.SasakiKotoko,
    MemberName.YoshidaAyanoChristie,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const jikochu: SingleRaw = {
  title: "ジコチューで行こう!",
  number: "21",
  release: "2018-08-08",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["ジコチューで行こう!"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["空扉"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["三角の空き地"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["自分じゃない感じ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["心のモノローグ"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["地球が丸いなら"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["あんなに好きだったのに..."].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.NakadaKana,
    MemberName.ItouRiria,
    MemberName.YamazakiRena,
    MemberName.SakaguchiTamami,
    MemberName.KitanoHinako,
    MemberName.TeradaRanze,
    MemberName.WatanabeMiria,
    MemberName.SatouKaede,
    MemberName.YoshidaAyanoChristie,
    MemberName.WadaMaaya,
    MemberName.KawagoHina,
    MemberName.NoujouAmi,
    MemberName.NakamuraReno,
    MemberName.ItouKarin,
    MemberName.SasakiKotoko,
    MemberName.MukaiHazuki,
    MemberName.ItouJunna,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.KuboShiori],
  },
};

const syncronicity: SingleRaw = {
  title: "シンクロニシティ",
  number: "20",
  release: "2018-04-25",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["シンクロニシティ"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["Against"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["雲になればいい"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["新しい世界"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["スカウトマン"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["トキトキメキメキ"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["言霊砲"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.UmezawaMinami,
    MemberName.WatanabeMiria,
    MemberName.NakadaKana,
    MemberName.SuzukiAyane,
    MemberName.SaitouYuuri,
    MemberName.YamazakiRena,
    MemberName.ItouRiria,
    MemberName.MukaiHazuki,
    MemberName.ItouKarin,
    MemberName.IwamotoRenka,
    MemberName.ItouJunna,
    MemberName.SakaguchiTamami,
    MemberName.SaitouChiharu,
    MemberName.SatouKaede,
    MemberName.NoujouAmi,
    MemberName.KawagoHina,
    MemberName.YoshidaAyanoChristie,
    MemberName.SasakiKotoko,
    MemberName.NakamuraReno,
    MemberName.WadaMaaya,
    MemberName.SagaraIori,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.KitanoHinako],
  },
};

const itsukadekirukara: SingleRaw = {
  title: "いつかできるから今日できる",
  number: "19",
  release: "2017-10-11",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["いつかできるから今日できる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["不眠症"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["まあいいか?"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["失恋お掃除人"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["My rule"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["僕の衝動"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["新しい花粉 〜ミュージカル「見知らぬ世界」より〜"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.WatanabeMiria,
    MemberName.HiguchiHina,
    MemberName.TeradaRanze,
    MemberName.NoujouAmi,
    MemberName.SuzukiAyane,
    MemberName.YamazakiRena,
    MemberName.SaitouChiharu,
    MemberName.SagaraIori,
    MemberName.SasakiKotoko,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.WadaMaaya,
    MemberName.ItouJunna,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouRiria,
      MemberName.IwamotoRenka,
      MemberName.UmezawaMinami,
      MemberName.OozonoMomoko,
      MemberName.KuboShiori,
      MemberName.SakaguchiTamami,
      MemberName.SatouKaede,
      MemberName.NakamuraReno,
      MemberName.MukaiHazuki,
      MemberName.YamashitaMizuki,
      MemberName.YoshidaAyanoChristie,
      MemberName.YodaYuuki,
    ],
    skips: [],
  },
};

const nigemizu: SingleRaw = {
  title: "逃げ水",
  number: "18",
  release: "2017-08-09",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["逃げ水"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["女は一人じゃ眠れない"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["ひと夏の長さより…"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["泣いたっていいじゃないか?"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["アンダー"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["ライブ神"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["未来の答え"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.WatanabeMiria,
    MemberName.NakamotoHimeka,
    MemberName.KitanoHinako,
    MemberName.TeradaRanze,
    MemberName.SaitouYuuri,
    MemberName.NakadaKana,
    MemberName.YamazakiRena,
    MemberName.SuzukiAyane,
    MemberName.ItouKarin,
    MemberName.ItouJunna,
    MemberName.SaitouChiharu,
    MemberName.NoujouAmi,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.SasakiKotoko,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouRiria,
      MemberName.IwamotoRenka,
      MemberName.UmezawaMinami,
      MemberName.KuboShiori,
      MemberName.SakaguchiTamami,
      MemberName.SatouKaede,
      MemberName.NakamuraReno,
      MemberName.MukaiHazuki,
      MemberName.YamashitaMizuki,
      MemberName.YoshidaAyanoChristie,
    ],
    skips: [],
  },
};

const influencer: SingleRaw = {
  title: "インフルエンサー",
  number: "17",
  release: "2017-03-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["インフルエンサー"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["人生を考えたくなる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["意外BREAK"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["Another Ghost"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["風船は生きている"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["三番目の風"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["当たり障りのない話"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.YamazakiRena,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.SaitouChiharu,
    MemberName.ItouKarin,
    MemberName.NoujouAmi,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.SasakiKotoko,
    MemberName.WadaMaaya,
    MemberName.ItouJunna,
    MemberName.KawamuraMahiro,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouRiria,
      MemberName.IwamotoRenka,
      MemberName.UmezawaMinami,
      MemberName.OozonoMomoko,
      MemberName.KuboShiori,
      MemberName.SakaguchiTamami,
      MemberName.SatouKaede,
      MemberName.NakamuraReno,
      MemberName.MukaiHazuki,
      MemberName.YamashitaMizuki,
      MemberName.YoshidaAyanoChristie,
      MemberName.YodaYuuki,
    ],
    skips: [MemberName.NakamotoHimeka],
  },
};

const sayonaranoimi: SingleRaw = {
  title: "サヨナラの意味",
  number: "16",
  release: "2016-11-09",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["サヨナラの意味"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["孤独な青空"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["あの教室"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["ブランコ"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["2度目のキスから"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["君に贈る花がない"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["ないものねだり"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KawamuraMahiro,
    MemberName.HiguchiHina,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.SaitouYuuri,
    MemberName.YamazakiRena,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.SaitouChiharu,
    MemberName.ItouJunna,
    MemberName.WadaMaaya,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.SasakiKotoko,
    MemberName.SagaraIori,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const hadashidesummer: SingleRaw = {
  title: "裸足でSummer",
  number: "15",
  release: "2016-07-27",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["裸足でSummer"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["僕だけの光"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["オフショアガール"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["命の真実 ミュージカル「林檎売りとカメムシ」"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["白米様"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["シークレットグラフィティー"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["行くあてのない僕たち"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.TeradaRanze,
    MemberName.ItouMarika,
    MemberName.HiguchiHina,
    MemberName.InoueSayuri,
    MemberName.WatanabeMiria,
    MemberName.SaitouChiharu,
    MemberName.SaitouYuuri,
    MemberName.ShinuchiMai,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.KawamuraMahiro,
    MemberName.YamazakiRena,
    MemberName.ItouJunna,
    MemberName.KawagoHina,
    MemberName.SuzukiAyane,
    MemberName.WadaMaaya,
    MemberName.SagaraIori,
    MemberName.SasakiKotoko,
    MemberName.ItouKarin,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const harujion: SingleRaw = {
  title: "ハルジオンが咲く頃",
  number: "14",
  release: "2016-03-23",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["ハルジオンが咲く頃"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 2,
      title: SONGS["遥かなるブータン"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.D, CdType.T],
    },
    {
      number: 3,
      title: SONGS["強がる蕾"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["急斜面"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["釣り堀"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["不等号"].title,
      inCdType: [CdType.D],
    },
    {
      number: 7,
      title: SONGS["憂鬱と風船ガム"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouYuuri,
    MemberName.TeradaRanze,
    MemberName.NakamotoHimeka,
    MemberName.KitanoHinako,
    MemberName.HiguchiHina,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.NakadaKana,
    MemberName.ShinuchiMai,
    MemberName.NoujouAmi,
    MemberName.SaitouChiharu,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.YamazakiRena,
    MemberName.SasakiKotoko,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.WadaMaaya,
    MemberName.ItouJunna,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const hanashitaidarekagairu: SingleRaw = {
  title: "今、話したい誰かがいる",
  number: "13",
  release: "2015-10-28",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["今、話したい誰かがいる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["嫉妬の権利"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["ポピパッパパー"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["大人への近道"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["悲しみの忘れ方"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["隙間"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KitanoHinako,
    MemberName.HoriMiona,
    MemberName.NakamotoHimeka,
    MemberName.TeradaRanze,
    MemberName.NakadaKana,
    MemberName.ShinuchiMai,
    MemberName.KawamuraMahiro,
    MemberName.NagashimaSeira,
    MemberName.NoujouAmi,
    MemberName.HiguchiHina,
    MemberName.SaitouChiharu,
    MemberName.SaitouYuuri,
    MemberName.KawagoHina,
    MemberName.WatanabeMiria,
    MemberName.YamazakiRena,
    MemberName.SasakiKotoko,
    MemberName.SagaraIori,
    MemberName.ItouJunna,
    MemberName.SuzukiAyane,
    MemberName.ItouKarin,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const taiyoknock: SingleRaw = {
  title: "太陽ノック",
  number: "12",
  release: "2015-07-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["太陽ノック"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T, CdType.L],
    },
    {
      number: 2,
      title: SONGS["もう少しの夢"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T, CdType.L],
    },
    {
      number: 3,
      title: SONGS["魚たちのLOVE SONG"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["無表情"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["別れ際、もっと好きになる"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["羽根の記憶"].title,
      inCdType: [CdType.T],
    },
    {
      number: 7,
      title: SONGS["制服を脱いでサヨナラを…"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KawamuraMahiro,
    MemberName.KitanoHinako,
    MemberName.HoriMiona,
    MemberName.NakamotoHimeka,
    MemberName.NakadaKana,
    MemberName.SagaraIori,
    MemberName.KawagoHina,
    MemberName.NagashimaSeira,
    MemberName.NoujouAmi,
    MemberName.SaitouChiharu,
    MemberName.WadaMaaya,
    MemberName.SasakiKotoko,
    MemberName.TeradaRanze,
    MemberName.ItouKarin,
    MemberName.WatanabeMiria,
    MemberName.SuzukiAyane,
    MemberName.ItouJunna,
    MemberName.HiguchiHina,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.YamazakiRena],
  },
};

const inochihautsukushii: SingleRaw = {
  title: "命は美しい",
  number: "11",
  release: "2015-03-18",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["命は美しい"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["あらかじめ語られるロマンス"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["立ち直り中"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["ごめんね ずっと…"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["君は僕と会わない方がよかったのかな"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["ボーダー"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouYuuri,
    MemberName.NakamotoHimeka,
    MemberName.InoueSayuri,
    MemberName.NoujouAmi,
    MemberName.NagashimaSeira,
    MemberName.NakadaKana,
    MemberName.ShinuchiMai,
    MemberName.KawamuraMahiro,
    MemberName.KitanoHinako,
    MemberName.KawagoHina,
    MemberName.HiguchiHina,
    MemberName.ItouKarin,
    MemberName.WadaMaaya,
    MemberName.SaitouChiharu,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouJunna,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
    ],
    skips: [],
  },
};

const nandomenoaozoraka: SingleRaw = {
  title: "何度目の青空か?",
  number: "10",
  release: "2014-10-08",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["何度目の青空か?"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["遠回りの愛情"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["転がった鐘を鳴らせ!"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["私、起きる。"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["あの日 僕は咄嗟に嘘をついた"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["Tender days"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouAsuka,
    MemberName.InoueSayuri,
    MemberName.ItouMarika,
    MemberName.NagashimaSeira,
    MemberName.NakamotoHimeka,
    MemberName.SaitouYuuri,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.KawamuraMahiro,
    MemberName.WadaMaaya,
    MemberName.HiguchiHina,
    MemberName.ItouKarin,
    MemberName.KawagoHina,
    MemberName.HatanakaSeira,
    MemberName.KitanoHinako,
    MemberName.YamatoRina,
    MemberName.ShinuchiMai,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouJunna,
      MemberName.SagaraIori,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
    ],
    skips: [],
  },
};

const natsunofreeandeasy: SingleRaw = {
  title: "夏のFree&Easy",
  number: "9",
  release: "2014-07-09",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["夏のFree&Easy"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["何もできずにそばにいる"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["その先の出口!"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["無口なライオン"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["ここにいる理由"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["僕が行かなきゃ誰が行くんだ?"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.KawagoHina,
    MemberName.SaitouAsuka,
    MemberName.ItouMarika,
    MemberName.HiguchiHina,
    MemberName.WadaMaaya,
    MemberName.NagashimaSeira,
    MemberName.NakadaKana,
    MemberName.NoujouAmi,
    MemberName.NakamotoHimeka,
    MemberName.KawamuraMahiro,
    MemberName.SaitouChiharu,
    MemberName.KitanoHinako,
    MemberName.HatanakaSeira,
    MemberName.ItouNene,
    MemberName.IchikiRena,
    MemberName.ShinuchiMai,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouKarin,
      MemberName.ItouJunna,
      MemberName.SagaraIori,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
      MemberName.YonetokuKyouka,
      MemberName.YadaRisako,
    ],
    skips: [MemberName.IkutaErika],
  },
};

const kizuitarakataomoi: SingleRaw = {
  title: "気づいたら片想い",
  number: "8",
  release: "2014-04-02",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["気づいたら片想い"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["ロマンスのスタート"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["吐息のメソッド"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["孤独兄弟"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["生まれたままで"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["ダンケシェーン"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.InoueSayuri,
    MemberName.SaitouAsuka,
    MemberName.ItouMarika,
    MemberName.HoshinoMinami,
    MemberName.SaitouYuuri,
    MemberName.NagashimaSeira,
    MemberName.NakadaKana,
    MemberName.EtouMisa,
    MemberName.KawagoHina,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
    MemberName.ItouNene,
    MemberName.IchikiRena,
    MemberName.ShinuchiMai,
    MemberName.HatanakaSeira,
    MemberName.YamatoRina,
    MemberName.NoujouAmi,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouKarin,
      MemberName.ItouJunna,
      MemberName.SasakiKotoko,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
      MemberName.YonetokuKyouka,
      MemberName.YadaRisako,
    ],
    skips: [MemberName.SagaraIori],
  },
};

const valletta: SingleRaw = {
  title: "バレッタ",
  number: "7",
  release: "2013-11-27",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["バレッタ"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["月の大きさ"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["私のために 誰かのために"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["そんなバカな…"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["初恋の人を今でも"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["やさしさとは"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.InoueSayuri,
    MemberName.HoshinoMinami,
    MemberName.SaitouYuuri,
    MemberName.NoujouAmi,
    MemberName.HiguchiHina,
    MemberName.NakadaKana,
    MemberName.NagashimaSeira,
    MemberName.KawamuraMahiro,
    MemberName.SaitouChiharu,
    MemberName.HatanakaSeira,
    MemberName.YamatoRina,
    MemberName.ItouNene,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [
      MemberName.ItouKarin,
      MemberName.ItouJunna,
      MemberName.KitanoHinako,
      MemberName.SasakiKotoko,
      MemberName.ShinuchiMai,
      MemberName.SuzukiAyane,
      MemberName.TeradaRanze,
      MemberName.YamazakiRena,
      MemberName.WatanabeMiria,
      MemberName.YonetokuKyouka,
      MemberName.YadaRisako,
      MemberName.NishikawaNanami,
    ],
    skips: [MemberName.IchikiRena, MemberName.SagaraIori],
  },
};

const girlsrule: SingleRaw = {
  title: "ガールズルール",
  number: "6",
  release: "2013-07-03",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["ガールズルール"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["世界で一番 孤独なLover"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["コウモリよ"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["扇風機"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["他の星から"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["人間という楽器"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.SaitouAsuka,
    MemberName.NakamotoHimeka,
    MemberName.NoujouAmi,
    MemberName.EtouMisa,
    MemberName.KawamuraMahiro,
    MemberName.ItouNene,
    MemberName.NagashimaSeira,
    MemberName.SaitouChiharu,
    MemberName.IchikiRena,
    MemberName.YamatoRina,
    MemberName.KawagoHina,
    MemberName.WadaMaaya,
    MemberName.KashiwaYukina,
    MemberName.HatanakaSeira,
    MemberName.MiyazawaSeira,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const kiminonahakibo: SingleRaw = {
  title: "君の名は希望",
  number: "5",
  release: "2013-03-31",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["君の名は希望"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["シャキイズム"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["ロマンティックいか焼き"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["13日の金曜日"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["でこぴん"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["サイコキネシスの可能性"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.ItouMarika,
    MemberName.SaitouYuuri,
    MemberName.SaitouAsuka,
    MemberName.KawamuraMahiro,
    MemberName.EtouMisa,
    MemberName.NoujouAmi,
    MemberName.IchikiRena,
    MemberName.YamatoRina,
    MemberName.WadaMaaya,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
    MemberName.KashiwaYukina,
    MemberName.AndouMikumo,
    MemberName.HatanakaSeira,
    MemberName.HiguchiHina,
    MemberName.KawagoHina,
    MemberName.MiyazawaSeira,
  ],
  behindPerformers: {
    trainees: [],
    skips: [],
  },
};

const seifukunomannequin: SingleRaw = {
  title: "制服のマネキン",
  number: "4",
  release: "2012-12-19",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["制服のマネキン"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["指望遠鏡"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["やさしさなら間に合ってる"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["ここじゃないどこか"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["春のメロディー"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["渋谷ブルース"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.SaitouYuuri,
    MemberName.NakadaKana,
    MemberName.EtouMisa,
    MemberName.ItouMarika,
    MemberName.KawagoHina,
    MemberName.HiguchiHina,
    MemberName.ItouNene,
    MemberName.KawamuraMahiro,
    MemberName.NakamotoHimeka,
    MemberName.HatanakaSeira,
    MemberName.NagashimaSeira,
    MemberName.MiyazawaSeira,
    MemberName.YamatoRina,
    MemberName.AndouMikumo,
    MemberName.WadaMaaya,
    MemberName.SaitouChiharu,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.KashiwaYukina],
  },
};

const hashirebicycle: SingleRaw = {
  title: "走れ!Bicycle",
  number: "3",
  release: "2012-08-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["走れ!Bicycle"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["せっかちなかたつむり"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["涙がまだ悲しみだった頃"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["人はなぜ走るのか?"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["音が出ないギター"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["海流の島よ"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.HiguchiHina,
    MemberName.ItouNene,
    MemberName.SaitouAsuka,
    MemberName.EtouMisa,
    MemberName.NoujouAmi,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.KashiwaYukina,
    MemberName.YamatoRina,
    MemberName.NagashimaSeira,
    MemberName.MiyazawaSeira,
    MemberName.AndouMikumo,
    MemberName.HatanakaSeira,
    MemberName.IwaseYumiko,
    MemberName.WadaMaaya,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.AkimotoManatsu],
  },
};

const oideshampoo: SingleRaw = {
  title: "おいでシャンプー",
  number: "2",
  release: "2012-05-02",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["おいでシャンプー"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["心の薬"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["偶然を言い訳にして"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["水玉模様"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["狼に口笛を"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["ハウス!"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.FukagawaMai,
    MemberName.ItouMarika,
    MemberName.WakatsukiYumi,
    MemberName.KawagoHina,
    MemberName.KawamuraMahiro,
    MemberName.SaitouChiharu,
    MemberName.NagashimaSeira,
    MemberName.EtouMisa,
    MemberName.ItouNene,
    MemberName.SaitouAsuka,
    MemberName.NakamotoHimeka,
    MemberName.HiguchiHina,
    MemberName.KashiwaYukina,
    MemberName.AndouMikumo,
    MemberName.YamatoRina,
    MemberName.NoujouAmi,
    MemberName.WadaMaaya,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.AkimotoManatsu],
  },
};

const gurugurucurtain: SingleRaw = {
  title: "ぐるぐるカーテン",
  number: "1",
  release: "2012-02-22",
  hasArtworks: true,
  artworkTypes: [CdType.A, CdType.B, CdType.C, CdType.T],
  shopping: [],
  songs: [
    {
      number: 1,
      title: SONGS["ぐるぐるカーテン"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 2,
      title: SONGS["左胸の勇気"].title,
      inCdType: [CdType.A, CdType.B, CdType.C, CdType.T],
    },
    {
      number: 3,
      title: SONGS["乃木坂の詩"].title,
      inCdType: [CdType.A],
    },
    {
      number: 4,
      title: SONGS["会いたかったかもしれない"].title,
      inCdType: [CdType.B],
    },
    {
      number: 5,
      title: SONGS["失いたくないから"].title,
      inCdType: [CdType.C],
    },
    {
      number: 6,
      title: SONGS["白い雲にのって"].title,
      inCdType: [CdType.T],
    },
  ],
  underMembers: [
    MemberName.AndouMikumo,
    MemberName.IwaseYumiko,
    MemberName.ItouNene,
    MemberName.HatanakaSeira,
    MemberName.ItouMarika,
    MemberName.WadaMaaya,
    MemberName.NakamotoHimeka,
    MemberName.SaitouChiharu,
    MemberName.YamatoRina,
    MemberName.NagashimaSeira,
    MemberName.HiguchiHina,
    MemberName.KawagoHina,
    MemberName.WakatsukiYumi,
    MemberName.KashiwaYukina,
    MemberName.EtouMisa,
    MemberName.FukagawaMai,
    MemberName.MiyazawaSeira,
  ],
  behindPerformers: {
    trainees: [],
    skips: [MemberName.AkimotoManatsu],
  },
};

export const rawSingles: SinglesRawArray = [
  hogoshoku,
  yoakemade,
  singout,
  kaerimichi,
  jikochu,
  syncronicity,
  itsukadekirukara,
  nigemizu,
  influencer,
  sayonaranoimi,
  hadashidesummer,
  harujion,
  hanashitaidarekagairu,
  taiyoknock,
  inochihautsukushii,
  nandomenoaozoraka,
  natsunofreeandeasy,
  kizuitarakataomoi,
  valletta,
  girlsrule,
  kiminonahakibo,
  seifukunomannequin,
  hashirebicycle,
  oideshampoo,
  gurugurucurtain,
];
