import { SongRaw } from 'server/actors/Songs/models';
import { SongType } from 'server/actors/Songs/constants/songType';
import { createSongRaw } from 'server/actors/Songs/raw/creator';

export const OTHER_SONGS: SongRaw[] = [
  createSongRaw({
    title: '世界中の隣人よ',
    type: SongType.Special,
    creators: {
      lyrics: ['秋元康'],
      compose: ['taka'],
      arrange: ['taka'],
      direct: ['横堀光範'],
    },
    formations: {
      firstRow: [
        'akimotomanatsu',
        'ikutaerika',
        'saitouasuka',
        'shiraishimai',
        'takayamakazumi',
        'nakadakana',
        'higuchihina',
        'hoshinominami',
        'matsumurasayuri',
        'wadamaaya',
        'itoujunna',
        'kitanohinako',
        'shinuchimai',
        'suzukiayane',
        'teradaranze',
        'horimiona',
        'yamazakirena',
        'watanabemiria',
        'itouriria',
        'iwamotorenka',
        'umezawaminami',
        'oozonomomoko',
        'kuboshiori',
        'sakaguchitamami',
        'satoukaede',
        'nakamurareno',
        'mukaihazuki',
        'yamashitamizuki',
        'yoshidaayanochristie',
        'yodayuuki',
        'endousakura',
        'kakiharuka',
        'kakehashisayaka',
        'kanagawasaya',
        'kitagawayuri',
        'shibatayuna',
        'seimiyarei',
        'tamuramayu',
        'tsutsuiayame',
        'hayakawaseira',
        'yakubomio',
        'kuromiharuka',
        'satourika',
        'hayashiruna',
        'matsuomiyu',
        'yumikinao',
        'ikomarina',
        'ichikirena',
        'itoukarin',
        'etoumisa',
        'saitouchiharu',
        'saitouyuuri',
        'sagaraiori',
        'sakuraireika',
        'nishinonanase',
        'noujouami',
        'wakatsukiyumi',
      ],
    },
  }),
  createSongRaw({
    title: 'Route 246',
    type: SongType.Title,
    creators: {
      lyrics: ['秋元康'],
      compose: ['小室哲哉'],
      arrange: ['小室哲哉'],
      direct: ['maxilla'],
    },
    formations: {
      firstRow: [
        'yodayuuki',
        'ikutaerika',
        'saitouasuka',
        'endousakura',
        'kakiharuka',
      ],
      secondRow: [
        'umezawaminami',
        'horimiona',
        'yamashitamizuki',
        'kuboshiori',
        'akimotomanatsu',
        'matsumurasayuri',
      ],
      thirdRow: [
        'shinuchimai',
        'kitanohinako',
        'oozonomomoko',
        'tsutsuiayame',
        'hoshinominami',
        'iwamotorenka',
        'takayamakazumi',
      ],
    },
    center: ['saitouasuka'],
    fukujin: 'row-1-2',
  }),
  createSongRaw({
    title: '１・２・３',
    type: SongType.Unit,
    creators: {
      lyrics: ['まふまふ'],
      compose: ['まふまふ'],
      arrange: ['APAZZI', 'Akira Sunset'],
      direct: ['月田茂'],
    },
    unit: 'からあげ姉妹',
    formations: {
      firstRow: ['ikutaerika', 'matsumurasayuri'],
    },
  }),
];
