import { SongRaw } from 'server/actors/Songs/models';
import { SongType } from 'server/actors/Songs/constants/songType';

import { createSongRaw } from 'server/actors/Songs/raw/creator';
import { MemberNameKey } from 'server/actors/Members/constants/memberName';
import { UnitName } from 'server/actors/Units/constants/unitName';

export const OTHER_SONGS: SongRaw[] = [
  createSongRaw({
    title: '世界中の隣人よ',
    type: SongType.Special,
    creators: {
      lyrics: ['秋元康'],
      compose: ['taka'],
      arrange: ['taka'],
      direct: ['横堀光範'],
    },
    formations: {
      firstRow: [
        MemberNameKey.AkimotoManatsu,
        MemberNameKey.IkutaErika,
        MemberNameKey.SaitouAsuka,
        MemberNameKey.ShiraishiMai,
        MemberNameKey.TakayamaKazumi,
        MemberNameKey.NakadaKana,
        MemberNameKey.HiguchiHina,
        MemberNameKey.HoshinoMinami,
        MemberNameKey.MatsumuraSayuri,
        MemberNameKey.WadaMaaya,
        MemberNameKey.ItouJunna,
        MemberNameKey.KitanoHinako,
        MemberNameKey.ShinuchiMai,
        MemberNameKey.SuzukiAyane,
        MemberNameKey.TeradaRanze,
        MemberNameKey.HoriMiona,
        MemberNameKey.YamazakiRena,
        MemberNameKey.WatanabeMiria,
        MemberNameKey.ItouRiria,
        MemberNameKey.IwamotoRenka,
        MemberNameKey.UmezawaMinami,
        MemberNameKey.OozonoMomoko,
        MemberNameKey.KuboShiori,
        MemberNameKey.SakaguchiTamami,
        MemberNameKey.SatouKaede,
        MemberNameKey.NakamuraReno,
        MemberNameKey.MukaiHazuki,
        MemberNameKey.YamashitaMizuki,
        MemberNameKey.YoshidaAyanoChristie,
        MemberNameKey.YodaYuuki,
        MemberNameKey.EndouSakura,
        MemberNameKey.KakiHaruka,
        MemberNameKey.KakehashiSayaka,
        MemberNameKey.KanagawaSaya,
        MemberNameKey.KitagawaYuri,
        MemberNameKey.ShibataYuna,
        MemberNameKey.SeimiyaRei,
        MemberNameKey.TamuraMayu,
        MemberNameKey.TsutsuiAyame,
        MemberNameKey.HayakawaSeira,
        MemberNameKey.YakuboMio,
        MemberNameKey.KuromiHaruka,
        MemberNameKey.SatouRika,
        MemberNameKey.HayashiRuna,
        MemberNameKey.MatsuoMiyu,
        MemberNameKey.YumikiNao,
        MemberNameKey.IkomaRina,
        MemberNameKey.IchikiRena,
        MemberNameKey.ItouKarin,
        MemberNameKey.EtouMisa,
        MemberNameKey.SaitouChiharu,
        MemberNameKey.SaitouYuuri,
        MemberNameKey.SagaraIori,
        MemberNameKey.SakuraiReika,
        MemberNameKey.NishinoNanase,
        MemberNameKey.NoujouAmi,
        MemberNameKey.WakatsukiYumi,
      ],
    },
  }),
  createSongRaw({
    title: 'Route 246',
    type: SongType.Title,
    creators: {
      lyrics: ['秋元康'],
      compose: ['小室哲哉'],
      arrange: ['小室哲哉'],
      direct: ['maxilla'],
    },
    formations: {
      firstRow: [
        MemberNameKey.YodaYuuki,
        MemberNameKey.IkutaErika,
        MemberNameKey.SaitouAsuka,
        MemberNameKey.EndouSakura,
        MemberNameKey.KakiHaruka,
      ],
      secondRow: [
        MemberNameKey.UmezawaMinami,
        MemberNameKey.HoriMiona,
        MemberNameKey.YamashitaMizuki,
        MemberNameKey.KuboShiori,
        MemberNameKey.AkimotoManatsu,
        MemberNameKey.MatsumuraSayuri,
      ],
      thirdRow: [
        MemberNameKey.ShinuchiMai,
        MemberNameKey.KitanoHinako,
        MemberNameKey.OozonoMomoko,
        MemberNameKey.TsutsuiAyame,
        MemberNameKey.HoshinoMinami,
        MemberNameKey.IwamotoRenka,
        MemberNameKey.TakayamaKazumi,
      ],
    },
    center: [MemberNameKey.SaitouAsuka],
    fukujin: 'row-1-2',
  }),
  createSongRaw({
    title: '１・２・３',
    type: SongType.Unit,
    creators: {
      lyrics: ['まふまふ'],
      compose: ['まふまふ'],
      arrange: ['APAZZI', 'Akira Sunset'],
      direct: ['月田茂'],
    },
    unit: UnitName.Karaageshimai,
    formations: {
      firstRow: [MemberNameKey.IkutaErika, MemberNameKey.MatsumuraSayuri],
    },
  }),
];
