import { SongRaw } from "server/actors/Songs/models";
import { SongType } from "server/constants/commons";
import { SONGS } from "server/constants/songs";
import { createSongRaw } from "server/actors/Songs/raw/creator";
import { MemberName } from "server/constants/names";

export const OTHER_SONGS: SongRaw[] = [
  createSongRaw({
    title: SONGS["世界中の隣人よ"].title,
    type: SongType.Special,
    creators: {
      lyrics: ["秋元康"],
      compose: ["taka"],
      arrange: ["taka"],
      direct: ["横堀光範"],
    },
    formations: {
      firstRow: [
        MemberName.AkimotoManatsu,
        MemberName.IkutaErika,
        MemberName.SaitouAsuka,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.HiguchiHina,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.WadaMaaya,
        MemberName.ItouJunna,
        MemberName.KitanoHinako,
        MemberName.ShinuchiMai,
        MemberName.SuzukiAyane,
        MemberName.TeradaRanze,
        MemberName.HoriMiona,
        MemberName.YamazakiRena,
        MemberName.WatanabeMiria,
        MemberName.ItouRiria,
        MemberName.IwamotoRenka,
        MemberName.UmezawaMinami,
        MemberName.OozonoMomoko,
        MemberName.KuboShiori,
        MemberName.SakaguchiTamami,
        MemberName.SatouKaede,
        MemberName.NakamuraReno,
        MemberName.MukaiHazuki,
        MemberName.YamashitaMizuki,
        MemberName.YoshidaAyanoChristie,
        MemberName.YodaYuuki,
        MemberName.EndouSakura,
        MemberName.KakiHaruka,
        MemberName.KakehashiSayaka,
        MemberName.KanagawaSaya,
        MemberName.KitagawaYuri,
        MemberName.ShibataYuna,
        MemberName.SeimiyaRei,
        MemberName.TamuraMayu,
        MemberName.TsutsuiAyame,
        MemberName.HayakawaSeira,
        MemberName.YakuboMio,
        MemberName.KuromiHaruka,
        MemberName.SatouRika,
        MemberName.HayashiRuna,
        MemberName.MatsuoMiyu,
        MemberName.YumikiNao,
        MemberName.IkomaRina,
        MemberName.IchikiRena,
        MemberName.ItouKarin,
        MemberName.EtouMisa,
        MemberName.SaitouChiharu,
        MemberName.SaitouYuuri,
        MemberName.SagaraIori,
        MemberName.SakuraiReika,
        MemberName.NishinoNanase,
        MemberName.NoujouAmi,
        MemberName.WakatsukiYumi,
      ],
    },
  }),
];
