import { createSingleRaw } from 'db/src/actors/Discography/raw/creators';

export const THIRTY_FIRST_SINGLE = createSingleRaw({
  title: 'ここにはないもの',
  number: '31',
  release: '2022-12-07',
  cdTypes: ['A', 'B', 'C', 'D', 'T'],
  songs: [
    { title: 'ここにはないもの', inCdType: ['A', 'B', 'C', 'D', 'T'] },
    { title: '悪い成分', inCdType: ['A', 'B', 'C', 'D', 'T'] },
    { title: 'これから', inCdType: ['A'] },
    { title: '銭湯ラプソディー', inCdType: ['B'] },
    { title: 'アトノマツリ', inCdType: ['C'] },
    { title: '甘いエビデンス', inCdType: ['D'] },
    { title: '17分間', inCdType: ['T'] },
  ],
  underMembers: [
    'itouriria',
    'satoukaede',
    'nakamurareno',
    'mukaihazuki',
    'yoshidaayanochristie',
    'kitagawayuri',
    'kuromiharuka',
    'satourika',
    'matsuomiyu',
    'yakubomio',
  ],
  skips: ['seimiyarei', 'kakehashisayaka'],
  trainees: [
    'iokimao',
    'ikedateresa',
    'ichinosemiku',
    'inouenagi',
    'okamotohina',
    'ogawaaya',
    'okudairoha',
    'kawasakisakura',
    'sugawarasatsuki',
    'tomisatonao',
    'nakanishiaruno',
  ],
});
