import { SongRaw } from "server/actors/Songs/models";
import { createSongRaw } from "server/actors/Songs/raw/creator";
import { FukujinType, SongType } from "server/constants/commons";
import { MemberName } from "server/constants/names";
import { SongTitle } from "server/constants/songs";

export const FIRST_SINGLE_SONGS: SongRaw[] = [
  createSongRaw({
    title: SongTitle.GuruguruCurtain,
    type: SongType.Title,
    creators: {
      lyrics: ["秋元康"],
      compose: ["黒須克彦"],
      arrange: ["湯浅篤"],
      direct: ["操上和美"],
    },
    center: [MemberName.IkomaRina],
    fukujin: FukujinType.RowOneTwo,
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.HoshinoMinami,
      ],
      secondRow: [
        MemberName.HashimotoNanami,
        MemberName.MatsumuraSayuri,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
      ],
      thirdRow: [
        MemberName.KawamuraMahiro,
        MemberName.NoujouAmi,
        MemberName.NishinoNanase,
        MemberName.SaitouAsuka,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.InoueSayuri,
        MemberName.NakadaKana,
        MemberName.IchikiRena,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Hidarimunenoyuuki,
    type: SongType.Under,
    creators: {
      lyrics: ["秋元康"],
      compose: ["小内喜文"],
      arrange: ["佐々木裕"],
    },
    center: [MemberName.HatanakaSeira],
    formations: {
      firstRow: [
        MemberName.AndouMikumo,
        MemberName.IwaseYumiko,
        MemberName.ItouNene,
        MemberName.HatanakaSeira,
        MemberName.ItouMarika,
        MemberName.WadaMaaya,
        MemberName.NakamotoHimeka,
      ],
      secondRow: [
        MemberName.SaitouChiharu,
        MemberName.YamatoRina,
        MemberName.NagashimaSeira,
        MemberName.HiguchiHina,
        MemberName.KawagoHina,
        MemberName.WakatsukiYumi,
        MemberName.KashiwaYukina,
        MemberName.EtouMisa,
        MemberName.FukagawaMai,
        MemberName.MiyazawaSeira,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Nogizakanouta,
    type: SongType.Coupling,
    creators: {
      lyrics: ["秋元康"],
      compose: ["井手コウジ"],
      arrange: ["井手コウジ"],
      direct: ["南流石"],
    },
    center: [MemberName.IkomaRina],
    formations: {
      firstRow: [
        MemberName.AndouMikumo,
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.IchikiRena,
        MemberName.ItouNene,
        MemberName.ItouMarika,
        MemberName.InoueSayuri,
        MemberName.IwaseYumiko,
        MemberName.EtouMisa,
        MemberName.KashiwaYukina,
        MemberName.KawagoHina,
        MemberName.KawamuraMahiro,
        MemberName.SaitouAsuka,
        MemberName.SaitouChiharu,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NagashimaSeira,
        MemberName.NakadaKana,
        MemberName.NakamotoHimeka,
        MemberName.NishinoNanase,
        MemberName.NoujouAmi,
        MemberName.HashimotoNanami,
        MemberName.HatanakaSeira,
        MemberName.HiguchiHina,
        MemberName.FukagawaMai,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.MiyazawaSeira,
        MemberName.YamatoRina,
        MemberName.WakatsukiYumi,
        MemberName.WadaMaaya,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Aitakattakamoshirenai,
    type: SongType.Coupling,
    creators: {
      lyrics: ["秋元康"],
      compose: ["BOUNCEBACK", "MIKOTO"],
      arrange: ["野中雄一"],
      direct: ["久保茂昭"],
    },
    center: [MemberName.IkomaRina],
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.IchikiRena,
        MemberName.ItouNene,
        MemberName.ItouMarika,
        MemberName.InoueSayuri,
        MemberName.EtouMisa,
        MemberName.KawamuraMahiro,
        MemberName.SaitouAsuka,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.NishinoNanase,
        MemberName.NoujouAmi,
        MemberName.HashimotoNanami,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
        MemberName.MiyazawaSeira,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Ushinaitakunaikara,
    type: SongType.Coupling,
    creators: {
      lyrics: ["秋元康"],
      compose: ["蛯原ランス"],
      arrange: ["塩川満己"],
      direct: ["丸山健志"],
    },
    center: [MemberName.IkomaRina, MemberName.IkutaErika],
    formations: {
      firstRow: [
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.IchikiRena,
        MemberName.InoueSayuri,
        MemberName.KawamuraMahiro,
        MemberName.SaitouAsuka,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.NagashimaSeira,
        MemberName.NakamotoHimeka,
        MemberName.NishinoNanase,
        MemberName.NoujouAmi,
        MemberName.HashimotoNanami,
        MemberName.HatanakaSeira,
        MemberName.FukagawaMai,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
      ],
    },
  }),
  createSongRaw({
    title: SongTitle.Shiroikumoninotte,
    type: SongType.Coupling,
    creators: {
      lyrics: ["秋元康"],
      compose: ["太田美知彦"],
      arrange: ["太田美知彦"],
    },
    center: [MemberName.IkomaRina],
    formations: {
      firstRow: [
        MemberName.AndouMikumo,
        MemberName.IkutaErika,
        MemberName.IkomaRina,
        MemberName.IchikiRena,
        MemberName.InoueSayuri,
        MemberName.IwaseYumiko,
        MemberName.KawagoHina,
        MemberName.KawamuraMahiro,
        MemberName.SaitouAsuka,
        MemberName.SaitouChiharu,
        MemberName.SaitouYuuri,
        MemberName.SakuraiReika,
        MemberName.ShiraishiMai,
        MemberName.TakayamaKazumi,
        MemberName.NakadaKana,
        MemberName.NishinoNanase,
        MemberName.NoujouAmi,
        MemberName.HashimotoNanami,
        MemberName.HoshinoMinami,
        MemberName.MatsumuraSayuri,
      ],
    },
  }),
];
