const NOGIZAKA_ARTIST_ID = '08lN7bm4Etec8ETFxaTUmq';
// const NOGIZAKA_ARTIST_NAME = 'Nogizaka46';

const KARAAGESHIMAI_ARTIST_ID = '0LVnnZTQ4h3ywlT5tPi7sl';
// const KARAAGESHIMAI_ARTIST_NAME = 'からあげ姉妹';

export const SPOTIFY_NOGIZAKA_ARTIST_IDS = [
  NOGIZAKA_ARTIST_ID,
  KARAAGESHIMAI_ARTIST_ID,
];
